UPDATE `Product_Size` SET `dimension`= '- Weight 40+ lbs<br>- Length 19-22.5 inch<br>- Thickness  1 inch' WHERE `item_no`=20001 and `size`= 'XL';
UPDATE `Product_Size` SET `dimension`= '- Weight 30-40 lbs<br>- Length 15-18 inch<br>- Thickness  7/8 inch' WHERE `item_no`=20001 and `size`= 'L';
UPDATE `Product_Size` SET `dimension`= '- Weight 12-30 lbs<br>- Length  12.5-15  inch<br>- Thickness  5/8 inch' WHERE `item_no`=20001 and `size`= 'M';
UPDATE `Product_Size` SET `dimension`= '- Weight 5-12 lbs<br>- Length 10-13 inch<br>- Thickness  1/2  inch' WHERE `item_no`=20001 and `size`= 'S';
UPDATE `Product_Size` SET `dimension`= '- Weight 40+ lbs<br>- Length 19-22.5 inch<br>- Thickness  1 inch' WHERE `item_no`=20002 and `size`= 'XL';
UPDATE `Product_Size` SET `dimension`= '- Weight 30-40 lbs<br>- Length 15-18 inch<br>- Thickness  7/8 inch' WHERE `item_no`=20002 and `size`= 'L';
UPDATE `Product_Size` SET `dimension`= '- Weight 12-30 lbs<br>- Length  12.5-15  inch<br>- Thickness  5/8 inch' WHERE `item_no`=20002 and `size`= 'M';
UPDATE `Product_Size` SET `dimension`= '- Weight 5-12 lbs<br>- Length 10-13 inch<br>- Thickness  1/2  inch' WHERE `item_no`=20002 and `size`= 'S';
UPDATE `Product_Size` SET `dimension`= '- Weight 40+ lbs<br>- Length 19-22.5 inch<br>- Thickness  1 inch' WHERE `item_no`=20003 and `size`= 'XL';
UPDATE `Product_Size` SET `dimension`= '- Weight 30-40 lbs<br>- Length 15-18 inch<br>- Thickness  7/8 inch' WHERE `item_no`=20003 and `size`= 'L';
UPDATE `Product_Size` SET `dimension`= '- Weight 12-30 lbs<br>- Length  12.5-15  inch<br>- Thickness  5/8 inch' WHERE `item_no`=20003 and `size`= 'M';
UPDATE `Product_Size` SET `dimension`= '- Weight 5-12 lbs<br>- Length 10-13 inch<br>- Thickness  1/2  inch' WHERE `item_no`=20003 and `size`= 'S';
UPDATE `Product_Size` SET `dimension`= '- Weight 40+ lbs<br>- Length 19-22.5 inch<br>- Thickness  1 inch' WHERE `item_no`=20004 and `size`= 'XL';
UPDATE `Product_Size` SET `dimension`= '- Weight 30-40 lbs<br>- Length 15-18 inch<br>- Thickness  7/8 inch' WHERE `item_no`=20004 and `size`= 'L';
UPDATE `Product_Size` SET `dimension`= '- Weight 12-30 lbs<br>- Length  12.5-15  inch<br>- Thickness  5/8 inch' WHERE `item_no`=20004 and `size`= 'M';
UPDATE `Product_Size` SET `dimension`= '- Weight 5-12 lbs<br>- Length 10-13 inch<br>- Thickness  1/2  inch' WHERE `item_no`=20004 and `size`= 'S';
UPDATE `Product_Size` SET `dimension`= '- Weight 40+ lbs<br>- Length 19-22.5 inch<br>- Thickness  1 inch' WHERE `item_no`=20005 and `size`= 'XL';
UPDATE `Product_Size` SET `dimension`= '- Weight 30-40 lbs<br>- Length 15-18 inch<br>- Thickness  7/8 inch' WHERE `item_no`=20005 and `size`= 'L';
UPDATE `Product_Size` SET `dimension`= '- Weight 12-30 lbs<br>- Length  12.5-15  inch<br>- Thickness  5/8 inch' WHERE `item_no`=20005 and `size`= 'M';
UPDATE `Product_Size` SET `dimension`= '- Weight 5-12 lbs<br>- Length 10-13 inch<br>- Thickness  1/2  inch' WHERE `item_no`=20005 and `size`= 'S';
UPDATE `Product_Size` SET `dimension`= '- Weight 40+ lbs<br>- Length 19-22.5 inch<br>- Thickness  1 inch' WHERE `item_no`=20006 and `size`= 'XL';
UPDATE `Product_Size` SET `dimension`= '- Weight 30-40 lbs<br>- Length 15-18 inch<br>- Thickness  7/8 inch' WHERE `item_no`=20006 and `size`= 'L';
UPDATE `Product_Size` SET `dimension`= '- Weight 12-30 lbs<br>- Length  12.5-15  inch<br>- Thickness  5/8 inch' WHERE `item_no`=20006 and `size`= 'M';
UPDATE `Product_Size` SET `dimension`= '- Weight 5-12 lbs<br>- Length 10-13 inch<br>- Thickness  1/2  inch' WHERE `item_no`=20006 and `size`= 'S';
UPDATE `Product_Size` SET `dimension`= '- Weight 40+ lbs<br>- Length 19-27 inch<br>- Thickness  1 inch' WHERE `item_no`=20007 and `size`= 'XL';
UPDATE `Product_Size` SET `dimension`= '- Weight 30-40 lbs<br>- Length 13.5-18.5 inch<br>- Thickness  7/8 inch' WHERE `item_no`=20007 and `size`= 'L';
UPDATE `Product_Size` SET `dimension`= '- Weight 12-30 lbs<br>- Length  10.5-13.5  inch<br>- Thickness  5/8 inch' WHERE `item_no`=20007 and `size`= 'M';
UPDATE `Product_Size` SET `dimension`= '- Weight 5-12 lbs<br>- Length 9-12  inch<br>- Thickness  1/2  inch' WHERE `item_no`=20007 and `size`= 'S';
UPDATE `Product_Size` SET `dimension`= '- Weight 40+ lbs<br>- Length 19-22.5 inch<br>- Thickness  1 inch' WHERE `item_no`=20008 and `size`= 'XL';
UPDATE `Product_Size` SET `dimension`= '- Weight 30-40 lbs<br>- Length 15-18 inch<br>- Thickness  7/8 inch' WHERE `item_no`=20008 and `size`= 'L';
UPDATE `Product_Size` SET `dimension`= '- Weight 12-30 lbs<br>- Length  12.5-15  inch<br>- Thickness  5/8 inch' WHERE `item_no`=20008 and `size`= 'M';
UPDATE `Product_Size` SET `dimension`= '- Weight 5-12 lbs<br>- Length 10-13 inch<br>- Thickness  1/2  inch' WHERE `item_no`=20008 and `size`= 'S';
UPDATE `Product_Size` SET `dimension`= '- Weight 30-40 lbs<br>- Length 15-18 inch<br>- Thickness  7/8 inch' WHERE `item_no`=20009 and `size`= 'L';
UPDATE `Product_Size` SET `dimension`= '- Weight 12-30 lbs<br>- Length  12.5-15  inch<br>- Thickness  5/8 inch' WHERE `item_no`=20009 and `size`= 'M';
UPDATE `Product_Size` SET `dimension`= '- Weight 5-12 lbs<br>- Length 10-13 inch<br>- Thickness  1/2  inch' WHERE `item_no`=20009 and `size`= 'S';
UPDATE `Product_Size` SET `dimension`= '- Weight 40+ lbs<br>- Length 19-22.5 inch<br>- Thickness  1 inch' WHERE `item_no`=20010 and `size`= 'XL';
UPDATE `Product_Size` SET `dimension`= '- Weight 30-40 lbs<br>- Length 15-18 inch<br>- Thickness  7/8 inch' WHERE `item_no`=20010 and `size`= 'L';
UPDATE `Product_Size` SET `dimension`= '- Weight 12-30 lbs<br>- Length  12.5-15  inch<br>- Thickness  5/8 inch' WHERE `item_no`=20010 and `size`= 'M';
UPDATE `Product_Size` SET `dimension`= '- Weight 5-12 lbs<br>- Length 10-13 inch<br>- Thickness  1/2  inch' WHERE `item_no`=20010 and `size`= 'S';
UPDATE `Product_Size` SET `dimension`= '- Weight 30-40 lbs<br>- Length14 - 20 inches<br>- Thickness5/4 inch' WHERE `item_no`=20024 and `size`= 'M';
UPDATE `Product_Size` SET `dimension`= '- Weight 14-30 lbs<br>- Length11 - 16 inches<br>- Thickness5/8 inch' WHERE `item_no`=20024 and `size`= 'S';
UPDATE `Product_Size` SET `dimension`= '- Weight 30-40 lbs<br>- Length14 - 20 inches<br>- Thickness5/4 inch' WHERE `item_no`=20025 and `size`= 'M';
UPDATE `Product_Size` SET `dimension`= '- Weight 14-30 lbs<br>- Length11 - 16 inches<br>- Thickness5/8 inch' WHERE `item_no`=20025 and `size`= 'S';
UPDATE `Product_Size` SET `dimension`= '- Weight 30-40 lbs<br>- Length14 - 20 inches<br>- Thickness5/4 inch' WHERE `item_no`=20026 and `size`= 'M';
UPDATE `Product_Size` SET `dimension`= '- Weight 14-30 lbs<br>- Length11 - 16 inches<br>- Thickness5/8 inch' WHERE `item_no`=20026 and `size`= 'S';
UPDATE `Product_Size` SET `dimension`= '- Weight 30-40 lbs<br>- Length14 - 20 inches<br>- Thickness5/4 inch' WHERE `item_no`=20027 and `size`= 'M';
UPDATE `Product_Size` SET `dimension`= '- Weight 14-30 lbs<br>- Length11 - 16 inches<br>- Thickness5/8 inch' WHERE `item_no`=20027 and `size`= 'S';
UPDATE `Product_Size` SET `dimension`= '- Weight 30-40 lbs<br>- Length14 - 20 inches<br>- Thickness5/4 inch' WHERE `item_no`=20028 and `size`= 'M';
UPDATE `Product_Size` SET `dimension`= '- Weight 14-30 lbs<br>- Length11 - 16 inches<br>- Thickness5/8 inch' WHERE `item_no`=20028 and `size`= 'S';
UPDATE `Product_Size` SET `dimension`= '- Weight 30-40 lbs<br>- Length14 - 20 inches<br>- Thickness5/4 inch' WHERE `item_no`=20029 and `size`= 'M';
UPDATE `Product_Size` SET `dimension`= '- Weight 14-30 lbs<br>- Length11 - 16 inches<br>- Thickness5/8 inch' WHERE `item_no`=20029 and `size`= 'S';
UPDATE `Product_Size` SET `dimension`= '- Weight 30-40 lbs<br>- Length14 - 20 inches<br>- Thickness5/4 inch' WHERE `item_no`=20030 and `size`= 'M';
UPDATE `Product_Size` SET `dimension`= '- Weight 14-30 lbs<br>- Length11 - 16 inches<br>- Thickness5/8 inch' WHERE `item_no`=20030 and `size`= 'S';
UPDATE `Product_Size` SET `dimension`= '- Weight 30-40 lbs<br>- Length14 - 20 inches<br>- Thickness5/4 inch' WHERE `item_no`=20031 and `size`= 'M';
UPDATE `Product_Size` SET `dimension`= '- Weight 14-30 lbs<br>- Length11 - 16 inches<br>- Thickness5/8 inch' WHERE `item_no`=20031 and `size`= 'S';
UPDATE `Product_Size` SET `dimension`= '- Weight 30-40 lbs<br>- Length14 - 20 inches<br>- Thickness5/4 inch' WHERE `item_no`=20032 and `size`= 'M';
UPDATE `Product_Size` SET `dimension`= '- Weight 14-30 lbs<br>- Length11 - 16 inches<br>- Thickness5/8 inch' WHERE `item_no`=20032 and `size`= 'S';
UPDATE `Product_Size` SET `dimension`= '- Weight 30-40 lbs<br>- Length14 - 20 inches<br>- Thickness5/4 inch' WHERE `item_no`=20033 and `size`= 'M';
UPDATE `Product_Size` SET `dimension`= '- Weight 14-30 lbs<br>- Length11 - 16 inches<br>- Thickness5/8 inch' WHERE `item_no`=20033 and `size`= 'S';
UPDATE `Product_Size` SET `dimension`= '- Weight 30-40 lbs<br>- Length14 - 20 inches<br>- Thickness5/4 inch' WHERE `item_no`=20034 and `size`= 'M';
UPDATE `Product_Size` SET `dimension`= '- Weight 14-30 lbs<br>- Length11 - 16 inches<br>- Thickness5/8 inch' WHERE `item_no`=20034 and `size`= 'S';
UPDATE `Product_Size` SET `dimension`= '- Weight 30-40 lbs<br>- Length14 - 20 inches<br>- Thickness5/4 inch' WHERE `item_no`=20035 and `size`= 'M';
UPDATE `Product_Size` SET `dimension`= '- Weight 14-30 lbs<br>- Length11 - 16 inches<br>- Thickness5/8 inch' WHERE `item_no`=20035 and `size`= 'S';
UPDATE `Product_Size` SET `dimension`= '- Weight 30-40 lbs<br>- Length14 - 20 inches<br>- Thickness5/4 inch' WHERE `item_no`=20036 and `size`= 'M';
UPDATE `Product_Size` SET `dimension`= '- Weight 14-30 lbs<br>- Length11 - 16 inches<br>- Thickness5/8 inch' WHERE `item_no`=20036 and `size`= 'S';
UPDATE `Product_Size` SET `dimension`= '- Weight 30-40 lbs<br>- Length14 - 20 inches<br>- Thickness5/4 inch' WHERE `item_no`=20037 and `size`= 'M';
UPDATE `Product_Size` SET `dimension`= '- Weight 14-30 lbs<br>- Length11 - 16 inches<br>- Thickness5/8 inch' WHERE `item_no`=20037 and `size`= 'S';
UPDATE `Product_Size` SET `dimension`= '- Weight 14-30 lbs<br>- Length4 ft.<br>- Thickness5/8 inch' WHERE `item_no`=20038 and `size`= 'S';
UPDATE `Product_Size` SET `dimension`= '- Weight 14-30 lbs<br>- Length4 ft.<br>- Thickness5/8 inch' WHERE `item_no`=20039 and `size`= 'S';
UPDATE `Product_Size` SET `dimension`= '- Weight 14-30 lbs<br>- Length4 ft.<br>- Thickness5/8 inch' WHERE `item_no`=20040 and `size`= 'S';
UPDATE `Product_Size` SET `dimension`= '- Weight 14-30 lbs<br>- Length4 ft.<br>- Thickness5/8 inch' WHERE `item_no`=20041 and `size`= 'S';
UPDATE `Product_Size` SET `dimension`= '- Weight 14-30 lbs<br>- Length4 ft.<br>- Thickness5/8 inch' WHERE `item_no`=20042 and `size`= 'S';
UPDATE `Product_Size` SET `dimension`= '- Weight 14-30 lbs<br>- Length4 ft.<br>- Thickness5/8 inch' WHERE `item_no`=20043 and `size`= 'S';
UPDATE `Product_Size` SET `dimension`= '- Weight 14-30 lbs<br>- Length4 ft.<br>- Thickness5/8 inch' WHERE `item_no`=20044 and `size`= 'S';
UPDATE `Product_Size` SET `dimension`= '- Weight 14-30 lbs<br>- Length4 ft.<br>- Thickness5/8 inch' WHERE `item_no`=20045 and `size`= 'S';
UPDATE `Product_Size` SET `dimension`= '- Weight 14-30 lbs<br>- Length4 ft.<br>- Thickness5/8 inch' WHERE `item_no`=20046 and `size`= 'S';
UPDATE `Product_Size` SET `dimension`= '- Weight 14-30 lbs<br>- Length4 ft.<br>- Thickness5/8 inch' WHERE `item_no`=20047 and `size`= 'S';
UPDATE `Product_Size` SET `dimension`= '- Weight 14-30 lbs<br>- Length4 ft.<br>- Thickness5/8 inch' WHERE `item_no`=20048 and `size`= 'S';
UPDATE `Product_Size` SET `dimension`= '- Weight 14-30 lbs<br>- Length4 ft.<br>- Thickness5/8 inch' WHERE `item_no`=20049 and `size`= 'S';
UPDATE `Product_Size` SET `dimension`= '- Weight 14-30 lbs<br>- Length4 ft.<br>- Thickness5/8 inch' WHERE `item_no`=20050 and `size`= 'S';
UPDATE `Product_Size` SET `dimension`= '- Weight 14-30 lbs<br>- Length4 ft.<br>- Thickness5/8 inch' WHERE `item_no`=20051 and `size`= 'S';