UPDATE `Product_Size` SET `dimension`= '&nbsp&nbsp&nbsp- 12W x 12D x 6.5H inches<br>&nbsp&nbsp&nbsp- Weight - 10lbs<br>&nbsp&nbsp&nbsp- Holds up to 5.5 cups of dry food or 44 oz of water.' WHERE `item_no`=10001 AND `size`= 'L';
UPDATE `Product_Size` SET `dimension`= '&nbsp&nbsp&nbsp- 10W x 10D x 5H inches<br>&nbsp&nbsp&nbsp- Weight - 4lbs<br>&nbsp&nbsp&nbsp- Holds up to 4.5 cups of dry food or 36 oz of water.' WHERE `item_no`=10001 AND `size`= 'M';
UPDATE `Product_Size` SET `dimension`= '&nbsp&nbsp&nbsp- 8W x 8D x 3H inches<br>&nbsp&nbsp&nbsp- Weight - 2lbs<br>&nbsp&nbsp&nbsp- Holds up to 2 cups of dry food or 16 oz of water.' WHERE `item_no`=10001 AND `size`= 'S';
UPDATE `Product_Size` SET `dimension`= '&nbsp&nbsp&nbsp- 9.25W x 9.25D x 4.25H inches<br>&nbsp&nbsp&nbsp- Weight - 5lbs<br>&nbsp&nbsp&nbsp- Holds up to 5.5 cups of dry food or 44 oz of water' WHERE `item_no`=10002 AND `size`= 'L';
UPDATE `Product_Size` SET `dimension`= '&nbsp&nbsp&nbsp- 8W x 8D x 4H inches<br>&nbsp&nbsp&nbsp- Weight - 4lbs<br>&nbsp&nbsp&nbsp- Holds up to 4.5 cups of dry food or 36 oz of water.' WHERE `item_no`=10002 AND `size`= 'M';
UPDATE `Product_Size` SET `dimension`= '&nbsp&nbsp&nbsp- 6.50W x 6.50D x 3H inches<br>&nbsp&nbsp&nbsp- Weight - 1lbs<br>&nbsp&nbsp&nbsp- Holds up to 2 cups of dry food or 16 oz of water' WHERE `item_no`=10002 AND `size`= 'S';
UPDATE `Product_Size` SET `dimension`= '&nbsp&nbsp&nbsp- 14.50W x 8D x 5H inches<br>&nbsp&nbsp&nbsp- Weight - 2lbs<br>&nbsp&nbsp&nbsp- Holds up to 2 cups of dry food or 16 oz of water.' WHERE `item_no`=10003 AND `size`= 'S';
UPDATE `Product_Size` SET `dimension`= '&nbsp&nbsp&nbsp- 7.50W x 7.50D x 4.50H inches<br>&nbsp&nbsp&nbsp- Weight - 2lbs<br>&nbsp&nbsp&nbsp- Holds up to 2 cups of dry food or 16 oz of water.' WHERE `item_no`=10004 AND `size`= 'S';
UPDATE `Product_Size` SET `dimension`= '&nbsp&nbsp&nbsp- 7.50W x 7.50D x 4.50H inches<br>&nbsp&nbsp&nbsp- Weight - 2lbs<br>&nbsp&nbsp&nbsp- Holds up to 2 cups of dry food or 16 oz of water.' WHERE `item_no`=10005 AND `size`= 'S';
UPDATE `Product_Size` SET `dimension`= '&nbsp&nbsp&nbsp- 8.75W x 8.75D x 3.75H inches<br>&nbsp&nbsp&nbsp- Weight - 2.5lbs<br>&nbsp&nbsp&nbsp- Holds up to 5.5 cups of dry food or 44 oz of water.' WHERE `item_no`=10006 AND `size`= 'L';
UPDATE `Product_Size` SET `dimension`= '&nbsp&nbsp&nbsp- 8W x 8D x 3.25H inches<br>&nbsp&nbsp&nbsp- Weight - 2lbs<br>&nbsp&nbsp&nbsp- Holds up to 4.5 cups of dry food or 36 oz of water.' WHERE `item_no`=10006 AND `size`= 'M';
UPDATE `Product_Size` SET `dimension`= '&nbsp&nbsp&nbsp- 6.5W x 6.5D x 3H inches<br>&nbsp&nbsp&nbsp- Weight - 1lbs<br>&nbsp&nbsp&nbsp- Holds up to 2 cups of dry food or 16 oz of water.' WHERE `item_no`=10006 AND `size`= 'S';
UPDATE `Product_Size` SET `dimension`= '&nbsp&nbsp&nbsp- 10.5W x 10.5D x 4H inches<br>&nbsp&nbsp&nbsp- Weight - 4lbs<br>&nbsp&nbsp&nbsp- Holds up to 5.5 cups of dry food or 44 oz of water.' WHERE `item_no`=10007 AND `size`= 'L';
UPDATE `Product_Size` SET `dimension`= '&nbsp&nbsp&nbsp- 10W x 10D x 3.5H inches<br>&nbsp&nbsp&nbsp- Weight - 3lbs<br>&nbsp&nbsp&nbsp- Holds up to 4.5 cups of dry food or 36 oz of water.' WHERE `item_no`=10007 AND `size`= 'M';
UPDATE `Product_Size` SET `dimension`= '&nbsp&nbsp&nbsp- 8.5W x 8.5D x 2.75H inches<br>&nbsp&nbsp&nbsp- Weight - 2lbs<br>&nbsp&nbsp&nbsp- Holds up to 2 cups of dry food or 16 oz of water.' WHERE `item_no`=10007 AND `size`= 'S';
UPDATE `Product_Size` SET `dimension`= '&nbsp&nbsp&nbsp- 7.25W x 7.25D x 4.5H inches<br>&nbsp&nbsp&nbsp- Weight - 4lbs<br>&nbsp&nbsp&nbsp- Holds up to 2 cups of dry food or 16 oz of water.' WHERE `item_no`=10008 AND `size`= 'S';
UPDATE `Product_Size` SET `dimension`= '&nbsp&nbsp&nbsp- 10W x 10D x 12H inches<br>&nbsp&nbsp&nbsp- Weight - 12lbs<br>&nbsp&nbsp&nbsp- Holds up to 5.5 cups of dry food or 44 oz of water.' WHERE `item_no`=10009 AND `size`= 'L';
UPDATE `Product_Size` SET `dimension`= '&nbsp&nbsp&nbsp- 9W x 9D x 9H inches<br>&nbsp&nbsp&nbsp- Weight - 8lbs<br>&nbsp&nbsp&nbsp- Holds up to 4.5 cups of dry food or 36 oz of water.' WHERE `item_no`=10009 AND `size`= 'M';
UPDATE `Product_Size` SET `dimension`= '&nbsp&nbsp&nbsp- 8W x 8D x 4H inches<br>&nbsp&nbsp&nbsp- Weight - 3lbs<br>&nbsp&nbsp&nbsp- Holds up to 2 cups of dry food or 16 oz of water.' WHERE `item_no`=10009 AND `size`= 'S';
UPDATE `Product_Size` SET `dimension`= '&nbsp&nbsp&nbsp- 10W x 10D x 12H inches<br>&nbsp&nbsp&nbsp- Weight - 12lbs<br>&nbsp&nbsp&nbsp- Holds up to 5.5 cups of dry food or 44 oz of water.' WHERE `item_no`=10010 AND `size`= 'L';
UPDATE `Product_Size` SET `dimension`= '&nbsp&nbsp&nbsp- 9W x 9D x 9H inches<br>&nbsp&nbsp&nbsp- Weight - 8lbs<br>&nbsp&nbsp&nbsp- Holds up to 4.5 cups of dry food or 36 oz of water.' WHERE `item_no`=10010 AND `size`= 'M';
UPDATE `Product_Size` SET `dimension`= '&nbsp&nbsp&nbsp- 8W x 8D x 4H inches<br>&nbsp&nbsp&nbsp- Weight - 3lbs<br>&nbsp&nbsp&nbsp- Holds up to 2 cups of dry food or 16 oz of water.' WHERE `item_no`=10010 AND `size`= 'S';
UPDATE `Product_Size` SET `dimension`= '&nbsp&nbsp&nbsp- 15.75W x 8D x 4H inches<br>&nbsp&nbsp&nbsp- Weight - 3lbs<br>&nbsp&nbsp&nbsp- Holds up to 4.5 cups of dry food or 36 oz of water.' WHERE `item_no`=10011 AND `size`= 'M';
UPDATE `Product_Size` SET `dimension`= '&nbsp&nbsp&nbsp- 12.5W x 8.5D x 4H inches<br>&nbsp&nbsp&nbsp- Weight - 2lbs<br>&nbsp&nbsp&nbsp- Holds up to 2 cups of dry food or 16 oz of water.' WHERE `item_no`=10011 AND `size`= 'S';
UPDATE `Product_Size` SET `dimension`= '&nbsp&nbsp&nbsp- 7W x 2D x 3H inches<br>&nbsp&nbsp&nbsp- Weight - 4lbs<br>&nbsp&nbsp&nbsp- Holds up to 2.5 cups of dry food or 16 oz of water.' WHERE `item_no`=10012 AND `size`= 'M';
UPDATE `Product_Size` SET `dimension`= '&nbsp&nbsp&nbsp- 5W x 1.5D x 2.5H inches<br>&nbsp&nbsp&nbsp- Weight - 2lbs<br>&nbsp&nbsp&nbsp- Holds up to 1.5 cups of dry food or 12 oz of water.' WHERE `item_no`=10012 AND `size`= 'S';
UPDATE `Product_Size` SET `dimension`= '&nbsp&nbsp&nbsp- 7W x 2D x 3H inches<br>&nbsp&nbsp&nbsp- Weight - 4lbs<br>&nbsp&nbsp&nbsp- Holds up to 2.5 cups of dry food or 16 oz of water.' WHERE `item_no`=10013 AND `size`= 'M';
UPDATE `Product_Size` SET `dimension`= '&nbsp&nbsp&nbsp- 5W x 1.5D x 2.5H inches<br>&nbsp&nbsp&nbsp- Weight - 2lbs<br>&nbsp&nbsp&nbsp- Holds up to 1.5 cups of dry food or 12 oz of water.' WHERE `item_no`=10013 AND `size`= 'S';
UPDATE `Product_Size` SET `dimension`= '&nbsp&nbsp&nbsp- Weight 40+ lbs<br>&nbsp&nbsp&nbsp- Length 19-22.5 inch<br>&nbsp&nbsp&nbsp- Thickness  1 inch' WHERE `item_no`=20001 AND `size`= 'XL';
UPDATE `Product_Size` SET `dimension`= '&nbsp&nbsp&nbsp- Weight 30-40 lbs<br>&nbsp&nbsp&nbsp- Length 15-18 inch<br>&nbsp&nbsp&nbsp- Thickness  7/8 inch' WHERE `item_no`=20001 AND `size`= 'L';
UPDATE `Product_Size` SET `dimension`= '&nbsp&nbsp&nbsp- Weight 12-30 lbs<br>&nbsp&nbsp&nbsp- Length  12.5-15  inch<br>&nbsp&nbsp&nbsp- Thickness  5/8 inch' WHERE `item_no`=20001 AND `size`= 'M';
UPDATE `Product_Size` SET `dimension`= '&nbsp&nbsp&nbsp- Weight 5-12 lbs<br>&nbsp&nbsp&nbsp- Length 10-13 inch<br>&nbsp&nbsp&nbsp- Thickness  1/2  inch' WHERE `item_no`=20001 AND `size`= 'S';
UPDATE `Product_Size` SET `dimension`= '&nbsp&nbsp&nbsp- Weight 40+ lbs<br>&nbsp&nbsp&nbsp- Length 19-22.5 inch<br>&nbsp&nbsp&nbsp- Thickness  1 inch' WHERE `item_no`=20002 AND `size`= 'XL';
UPDATE `Product_Size` SET `dimension`= '&nbsp&nbsp&nbsp- Weight 30-40 lbs<br>&nbsp&nbsp&nbsp- Length 15-18 inch<br>&nbsp&nbsp&nbsp- Thickness  7/8 inch' WHERE `item_no`=20002 AND `size`= 'L';
UPDATE `Product_Size` SET `dimension`= '&nbsp&nbsp&nbsp- Weight 12-30 lbs<br>&nbsp&nbsp&nbsp- Length  12.5-15  inch<br>&nbsp&nbsp&nbsp- Thickness  5/8 inch' WHERE `item_no`=20002 AND `size`= 'M';
UPDATE `Product_Size` SET `dimension`= '&nbsp&nbsp&nbsp- Weight 5-12 lbs<br>&nbsp&nbsp&nbsp- Length 10-13 inch<br>&nbsp&nbsp&nbsp- Thickness  1/2  inch' WHERE `item_no`=20002 AND `size`= 'S';
UPDATE `Product_Size` SET `dimension`= '&nbsp&nbsp&nbsp- Weight 40+ lbs<br>&nbsp&nbsp&nbsp- Length 19-22.5 inch<br>&nbsp&nbsp&nbsp- Thickness  1 inch' WHERE `item_no`=20003 AND `size`= 'XL';
UPDATE `Product_Size` SET `dimension`= '&nbsp&nbsp&nbsp- Weight 30-40 lbs<br>&nbsp&nbsp&nbsp- Length 15-18 inch<br>&nbsp&nbsp&nbsp- Thickness  7/8 inch' WHERE `item_no`=20003 AND `size`= 'L';
UPDATE `Product_Size` SET `dimension`= '&nbsp&nbsp&nbsp- Weight 12-30 lbs<br>&nbsp&nbsp&nbsp- Length  12.5-15  inch<br>&nbsp&nbsp&nbsp- Thickness  5/8 inch' WHERE `item_no`=20003 AND `size`= 'M';
UPDATE `Product_Size` SET `dimension`= '&nbsp&nbsp&nbsp- Weight 5-12 lbs<br>&nbsp&nbsp&nbsp- Length 10-13 inch<br>&nbsp&nbsp&nbsp- Thickness  1/2  inch' WHERE `item_no`=20003 AND `size`= 'S';
UPDATE `Product_Size` SET `dimension`= '&nbsp&nbsp&nbsp- Weight 40+ lbs<br>&nbsp&nbsp&nbsp- Length 19-22.5 inch<br>&nbsp&nbsp&nbsp- Thickness  1 inch' WHERE `item_no`=20004 AND `size`= 'XL';
UPDATE `Product_Size` SET `dimension`= '&nbsp&nbsp&nbsp- Weight 30-40 lbs<br>&nbsp&nbsp&nbsp- Length 15-18 inch<br>&nbsp&nbsp&nbsp- Thickness  7/8 inch' WHERE `item_no`=20004 AND `size`= 'L';
UPDATE `Product_Size` SET `dimension`= '&nbsp&nbsp&nbsp- Weight 12-30 lbs<br>&nbsp&nbsp&nbsp- Length  12.5-15  inch<br>&nbsp&nbsp&nbsp- Thickness  5/8 inch' WHERE `item_no`=20004 AND `size`= 'M';
UPDATE `Product_Size` SET `dimension`= '&nbsp&nbsp&nbsp- Weight 5-12 lbs<br>&nbsp&nbsp&nbsp- Length 10-13 inch<br>&nbsp&nbsp&nbsp- Thickness  1/2  inch' WHERE `item_no`=20004 AND `size`= 'S';
UPDATE `Product_Size` SET `dimension`= '&nbsp&nbsp&nbsp- Weight 40+ lbs<br>&nbsp&nbsp&nbsp- Length 19-22.5 inch<br>&nbsp&nbsp&nbsp- Thickness  1 inch' WHERE `item_no`=20005 AND `size`= 'XL';
UPDATE `Product_Size` SET `dimension`= '&nbsp&nbsp&nbsp- Weight 30-40 lbs<br>&nbsp&nbsp&nbsp- Length 15-18 inch<br>&nbsp&nbsp&nbsp- Thickness  7/8 inch' WHERE `item_no`=20005 AND `size`= 'L';
UPDATE `Product_Size` SET `dimension`= '&nbsp&nbsp&nbsp- Weight 12-30 lbs<br>&nbsp&nbsp&nbsp- Length  12.5-15  inch<br>&nbsp&nbsp&nbsp- Thickness  5/8 inch' WHERE `item_no`=20005 AND `size`= 'M';
UPDATE `Product_Size` SET `dimension`= '&nbsp&nbsp&nbsp- Weight 5-12 lbs<br>&nbsp&nbsp&nbsp- Length 10-13 inch<br>&nbsp&nbsp&nbsp- Thickness  1/2  inch' WHERE `item_no`=20005 AND `size`= 'S';
UPDATE `Product_Size` SET `dimension`= '&nbsp&nbsp&nbsp- Weight 40+ lbs<br>&nbsp&nbsp&nbsp- Length 19-22.5 inch<br>&nbsp&nbsp&nbsp- Thickness  1 inch' WHERE `item_no`=20006 AND `size`= 'XL';
UPDATE `Product_Size` SET `dimension`= '&nbsp&nbsp&nbsp- Weight 30-40 lbs<br>&nbsp&nbsp&nbsp- Length 15-18 inch<br>&nbsp&nbsp&nbsp- Thickness  7/8 inch' WHERE `item_no`=20006 AND `size`= 'L';
UPDATE `Product_Size` SET `dimension`= '&nbsp&nbsp&nbsp- Weight 12-30 lbs<br>&nbsp&nbsp&nbsp- Length  12.5-15  inch<br>&nbsp&nbsp&nbsp- Thickness  5/8 inch' WHERE `item_no`=20006 AND `size`= 'M';
UPDATE `Product_Size` SET `dimension`= '&nbsp&nbsp&nbsp- Weight 5-12 lbs<br>&nbsp&nbsp&nbsp- Length 10-13 inch<br>&nbsp&nbsp&nbsp- Thickness  1/2  inch' WHERE `item_no`=20006 AND `size`= 'S';
UPDATE `Product_Size` SET `dimension`= '&nbsp&nbsp&nbsp- Weight 40+ lbs<br>&nbsp&nbsp&nbsp- Length 19-27 inch<br>&nbsp&nbsp&nbsp- Thickness  1 inch' WHERE `item_no`=20007 AND `size`= 'XL';
UPDATE `Product_Size` SET `dimension`= '&nbsp&nbsp&nbsp- Weight 30-40 lbs<br>&nbsp&nbsp&nbsp- Length 13.5-18.5 inch<br>&nbsp&nbsp&nbsp- Thickness  7/8 inch' WHERE `item_no`=20007 AND `size`= 'L';
UPDATE `Product_Size` SET `dimension`= '&nbsp&nbsp&nbsp- Weight 12-30 lbs<br>&nbsp&nbsp&nbsp- Length  10.5-13.5  inch<br>&nbsp&nbsp&nbsp- Thickness  5/8 inch' WHERE `item_no`=20007 AND `size`= 'M';
UPDATE `Product_Size` SET `dimension`= '&nbsp&nbsp&nbsp- Weight 5-12 lbs<br>&nbsp&nbsp&nbsp- Length 9-12  inch<br>&nbsp&nbsp&nbsp- Thickness  1/2  inch' WHERE `item_no`=20007 AND `size`= 'S';
UPDATE `Product_Size` SET `dimension`= '&nbsp&nbsp&nbsp- Weight 40+ lbs<br>&nbsp&nbsp&nbsp- Length 19-22.5 inch<br>&nbsp&nbsp&nbsp- Thickness  1 inch' WHERE `item_no`=20008 AND `size`= 'XL';
UPDATE `Product_Size` SET `dimension`= '&nbsp&nbsp&nbsp- Weight 30-40 lbs<br>&nbsp&nbsp&nbsp- Length 15-18 inch<br>&nbsp&nbsp&nbsp- Thickness  7/8 inch' WHERE `item_no`=20008 AND `size`= 'L';
UPDATE `Product_Size` SET `dimension`= '&nbsp&nbsp&nbsp- Weight 12-30 lbs<br>&nbsp&nbsp&nbsp- Length  12.5-15  inch<br>&nbsp&nbsp&nbsp- Thickness  5/8 inch' WHERE `item_no`=20008 AND `size`= 'M';
UPDATE `Product_Size` SET `dimension`= '&nbsp&nbsp&nbsp- Weight 5-12 lbs<br>&nbsp&nbsp&nbsp- Length 10-13 inch<br>&nbsp&nbsp&nbsp- Thickness  1/2  inch' WHERE `item_no`=20008 AND `size`= 'S';
UPDATE `Product_Size` SET `dimension`= '&nbsp&nbsp&nbsp- Weight 40+ lbs<br>&nbsp&nbsp&nbsp- Length 19-22.5 inch<br>&nbsp&nbsp&nbsp- Thickness  1 inch' WHERE `item_no`=20009 AND `size`= 'XL';
UPDATE `Product_Size` SET `dimension`= '&nbsp&nbsp&nbsp- Weight 30-40 lbs<br>&nbsp&nbsp&nbsp- Length 15-18 inch<br>&nbsp&nbsp&nbsp- Thickness  7/8 inch' WHERE `item_no`=20009 AND `size`= 'L';
UPDATE `Product_Size` SET `dimension`= '&nbsp&nbsp&nbsp- Weight 12-30 lbs<br>&nbsp&nbsp&nbsp- Length  12.5-15  inch<br>&nbsp&nbsp&nbsp- Thickness  5/8 inch' WHERE `item_no`=20009 AND `size`= 'M';
UPDATE `Product_Size` SET `dimension`= '&nbsp&nbsp&nbsp- Weight 5-12 lbs<br>&nbsp&nbsp&nbsp- Length 10-13 inch<br>&nbsp&nbsp&nbsp- Thickness  1/2  inch' WHERE `item_no`=20009 AND `size`= 'S';
UPDATE `Product_Size` SET `dimension`= '&nbsp&nbsp&nbsp- Weight 40+ lbs<br>&nbsp&nbsp&nbsp- Length 19-22.5 inch<br>&nbsp&nbsp&nbsp- Thickness  1 inch' WHERE `item_no`=20010 AND `size`= 'XL';
UPDATE `Product_Size` SET `dimension`= '&nbsp&nbsp&nbsp- Weight 30-40 lbs<br>&nbsp&nbsp&nbsp- Length 15-18 inch<br>&nbsp&nbsp&nbsp- Thickness  7/8 inch' WHERE `item_no`=20010 AND `size`= 'L';
UPDATE `Product_Size` SET `dimension`= '&nbsp&nbsp&nbsp- Weight 12-30 lbs<br>&nbsp&nbsp&nbsp- Length  12.5-15  inch<br>&nbsp&nbsp&nbsp- Thickness  5/8 inch' WHERE `item_no`=20010 AND `size`= 'M';
UPDATE `Product_Size` SET `dimension`= '&nbsp&nbsp&nbsp- Weight 5-12 lbs<br>&nbsp&nbsp&nbsp- Length 10-13 inch<br>&nbsp&nbsp&nbsp- Thickness  1/2  inch' WHERE `item_no`=20010 AND `size`= 'S';
UPDATE `Product_Size` SET `dimension`= '&nbsp&nbsp&nbsp- Weight 35+ lbs<br>&nbsp&nbsp&nbsp- Length 7 ft.<br>&nbsp&nbsp&nbsp- Thickness  12 mm' WHERE `item_no`=20011 AND `size`= 'L';
UPDATE `Product_Size` SET `dimension`= '&nbsp&nbsp&nbsp- Weight 12 - 30 lbs<br>&nbsp&nbsp&nbsp- Length 7 ft.<br>&nbsp&nbsp&nbsp- Thickness  8 mm' WHERE `item_no`=20011 AND `size`= 'M';
UPDATE `Product_Size` SET `dimension`= '&nbsp&nbsp&nbsp- Weight 5 - 12 lbs<br>&nbsp&nbsp&nbsp- Length  7 ft.<br>&nbsp&nbsp&nbsp- Thickness  6 mm' WHERE `item_no`=20011 AND `size`= 'S';
UPDATE `Product_Size` SET `dimension`= '&nbsp&nbsp&nbsp- Weight 35+ lbs<br>&nbsp&nbsp&nbsp- Length 7 ft.<br>&nbsp&nbsp&nbsp- Thickness  12 mm' WHERE `item_no`=20012 AND `size`= 'L';
UPDATE `Product_Size` SET `dimension`= '&nbsp&nbsp&nbsp- Weight 12 - 30 lbs<br>&nbsp&nbsp&nbsp- Length 7 ft.<br>&nbsp&nbsp&nbsp- Thickness  8 mm' WHERE `item_no`=20012 AND `size`= 'M';
UPDATE `Product_Size` SET `dimension`= '&nbsp&nbsp&nbsp- Weight 5 - 12 lbs<br>&nbsp&nbsp&nbsp- Length  7 ft.<br>&nbsp&nbsp&nbsp- Thickness  6 mm' WHERE `item_no`=20012 AND `size`= 'S';
UPDATE `Product_Size` SET `dimension`= '&nbsp&nbsp&nbsp- Weight 35+ lbs<br>&nbsp&nbsp&nbsp- Length 7 ft.<br>&nbsp&nbsp&nbsp- Thickness  12 mm' WHERE `item_no`=20013 AND `size`= 'L';
UPDATE `Product_Size` SET `dimension`= '&nbsp&nbsp&nbsp- Weight 12 - 30 lbs<br>&nbsp&nbsp&nbsp- Length 7 ft.<br>&nbsp&nbsp&nbsp- Thickness  8 mm' WHERE `item_no`=20013 AND `size`= 'M';
UPDATE `Product_Size` SET `dimension`= '&nbsp&nbsp&nbsp- Weight 5 - 12 lbs<br>&nbsp&nbsp&nbsp- Length  7 ft.<br>&nbsp&nbsp&nbsp- Thickness  6 mm' WHERE `item_no`=20013 AND `size`= 'S';
UPDATE `Product_Size` SET `dimension`= '&nbsp&nbsp&nbsp- Weight 35+ lbs<br>&nbsp&nbsp&nbsp- Length 7 ft.<br>&nbsp&nbsp&nbsp- Thickness  12 mm' WHERE `item_no`=20014 AND `size`= 'L';
UPDATE `Product_Size` SET `dimension`= '&nbsp&nbsp&nbsp- Weight 12 - 30 lbs<br>&nbsp&nbsp&nbsp- Length 7 ft.<br>&nbsp&nbsp&nbsp- Thickness  8 mm' WHERE `item_no`=20014 AND `size`= 'M';
UPDATE `Product_Size` SET `dimension`= '&nbsp&nbsp&nbsp- Weight 5 - 12 lbs<br>&nbsp&nbsp&nbsp- Length  7 ft.<br>&nbsp&nbsp&nbsp- Thickness  6 mm' WHERE `item_no`=20014 AND `size`= 'S';
UPDATE `Product_Size` SET `dimension`= '&nbsp&nbsp&nbsp- Weight 35+ lbs<br>&nbsp&nbsp&nbsp- Length 7 ft.<br>&nbsp&nbsp&nbsp- Thickness  12 mm' WHERE `item_no`=20015 AND `size`= 'L';
UPDATE `Product_Size` SET `dimension`= '&nbsp&nbsp&nbsp- Weight 12 - 30 lbs<br>&nbsp&nbsp&nbsp- Length 7 ft.<br>&nbsp&nbsp&nbsp- Thickness  8 mm' WHERE `item_no`=20015 AND `size`= 'M';
UPDATE `Product_Size` SET `dimension`= '&nbsp&nbsp&nbsp- Weight 5 - 12 lbs<br>&nbsp&nbsp&nbsp- Length  7 ft.<br>&nbsp&nbsp&nbsp- Thickness  6 mm' WHERE `item_no`=20015 AND `size`= 'S';
UPDATE `Product_Size` SET `dimension`= '&nbsp&nbsp&nbsp- Weight 35+ lbs<br>&nbsp&nbsp&nbsp- Length 7 ft.<br>&nbsp&nbsp&nbsp- Thickness  12 mm' WHERE `item_no`=20016 AND `size`= 'L';
UPDATE `Product_Size` SET `dimension`= '&nbsp&nbsp&nbsp- Weight 12 - 30 lbs<br>&nbsp&nbsp&nbsp- Length 7 ft.<br>&nbsp&nbsp&nbsp- Thickness  8 mm' WHERE `item_no`=20016 AND `size`= 'M';
UPDATE `Product_Size` SET `dimension`= '&nbsp&nbsp&nbsp- Weight 5 - 12 lbs<br>&nbsp&nbsp&nbsp- Length  7 ft.<br>&nbsp&nbsp&nbsp- Thickness  6 mm' WHERE `item_no`=20016 AND `size`= 'S';
UPDATE `Product_Size` SET `dimension`= '&nbsp&nbsp&nbsp- Weight 35+ lbs<br>&nbsp&nbsp&nbsp- Length 7 ft.<br>&nbsp&nbsp&nbsp- Thickness  12 mm' WHERE `item_no`=20017 AND `size`= 'L';
UPDATE `Product_Size` SET `dimension`= '&nbsp&nbsp&nbsp- Weight 12 - 30 lbs<br>&nbsp&nbsp&nbsp- Length 7 ft.<br>&nbsp&nbsp&nbsp- Thickness  8 mm' WHERE `item_no`=20017 AND `size`= 'M';
UPDATE `Product_Size` SET `dimension`= '&nbsp&nbsp&nbsp- Weight 5 - 12 lbs<br>&nbsp&nbsp&nbsp- Length  7 ft.<br>&nbsp&nbsp&nbsp- Thickness  6 mm' WHERE `item_no`=20017 AND `size`= 'S';
UPDATE `Product_Size` SET `dimension`= '&nbsp&nbsp&nbsp- Weight 35+ lbs<br>&nbsp&nbsp&nbsp- Length 7 ft.<br>&nbsp&nbsp&nbsp- Thickness  12 mm' WHERE `item_no`=20018 AND `size`= 'L';
UPDATE `Product_Size` SET `dimension`= '&nbsp&nbsp&nbsp- Weight 12 - 30 lbs<br>&nbsp&nbsp&nbsp- Length 7 ft.<br>&nbsp&nbsp&nbsp- Thickness  8 mm' WHERE `item_no`=20018 AND `size`= 'M';
UPDATE `Product_Size` SET `dimension`= '&nbsp&nbsp&nbsp- Weight 5 - 12 lbs<br>&nbsp&nbsp&nbsp- Length  7 ft.<br>&nbsp&nbsp&nbsp- Thickness  6 mm' WHERE `item_no`=20018 AND `size`= 'S';
UPDATE `Product_Size` SET `dimension`= '&nbsp&nbsp&nbsp- Weight 35+ lbs<br>&nbsp&nbsp&nbsp- Length 7 ft.<br>&nbsp&nbsp&nbsp- Thickness12 mm' WHERE `item_no`=20019 AND `size`= 'L';
UPDATE `Product_Size` SET `dimension`= '&nbsp&nbsp&nbsp- Weight 12 - 30 lbs<br>&nbsp&nbsp&nbsp- Length 7 ft.<br>&nbsp&nbsp&nbsp- Thickness8 mm' WHERE `item_no`=20019 AND `size`= 'M';
UPDATE `Product_Size` SET `dimension`= '&nbsp&nbsp&nbsp- Weight 5 - 12 lbs<br>&nbsp&nbsp&nbsp- Length7 ft.<br>&nbsp&nbsp&nbsp- Thickness6 mm' WHERE `item_no`=20019 AND `size`= 'S';
UPDATE `Product_Size` SET `dimension`= '&nbsp&nbsp&nbsp- Weight 35+ lbs<br>&nbsp&nbsp&nbsp- Length 7 ft.<br>&nbsp&nbsp&nbsp- Thickness12 mm' WHERE `item_no`=20020 AND `size`= 'L';
UPDATE `Product_Size` SET `dimension`= '&nbsp&nbsp&nbsp- Weight 12 - 30 lbs<br>&nbsp&nbsp&nbsp- Length 7 ft.<br>&nbsp&nbsp&nbsp- Thickness8 mm' WHERE `item_no`=20020 AND `size`= 'M';
UPDATE `Product_Size` SET `dimension`= '&nbsp&nbsp&nbsp- Weight 5 - 12 lbs<br>&nbsp&nbsp&nbsp- Length7 ft.<br>&nbsp&nbsp&nbsp- Thickness6 mm' WHERE `item_no`=20020 AND `size`= 'S';
UPDATE `Product_Size` SET `dimension`= '&nbsp&nbsp&nbsp- Weight 35+ lbs<br>&nbsp&nbsp&nbsp- Length 5 ft.<br>&nbsp&nbsp&nbsp- Thickness12 mm' WHERE `item_no`=20021 AND `size`= 'L';
UPDATE `Product_Size` SET `dimension`= '&nbsp&nbsp&nbsp- Weight 12 - 30 lbs<br>&nbsp&nbsp&nbsp- Length 5 ft.<br>&nbsp&nbsp&nbsp- Thickness8 mm' WHERE `item_no`=20021 AND `size`= 'M';
UPDATE `Product_Size` SET `dimension`= '&nbsp&nbsp&nbsp- Weight 5 - 12 lbs<br>&nbsp&nbsp&nbsp- Length5 ft.<br>&nbsp&nbsp&nbsp- Thickness6 mm' WHERE `item_no`=20021 AND `size`= 'S';
UPDATE `Product_Size` SET `dimension`= '&nbsp&nbsp&nbsp- Weight 35+ lbs<br>&nbsp&nbsp&nbsp- Length 5 ft.<br>&nbsp&nbsp&nbsp- Thickness12 mm' WHERE `item_no`=20022 AND `size`= 'L';
UPDATE `Product_Size` SET `dimension`= '&nbsp&nbsp&nbsp- Weight 12 - 30 lbs<br>&nbsp&nbsp&nbsp- Length 5 ft.<br>&nbsp&nbsp&nbsp- Thickness8 mm' WHERE `item_no`=20022 AND `size`= 'M';
UPDATE `Product_Size` SET `dimension`= '&nbsp&nbsp&nbsp- Weight 5 - 12 lbs<br>&nbsp&nbsp&nbsp- Length5 ft.<br>&nbsp&nbsp&nbsp- Thickness6 mm' WHERE `item_no`=20022 AND `size`= 'S';
UPDATE `Product_Size` SET `dimension`= '&nbsp&nbsp&nbsp- Weight 35+ lbs<br>&nbsp&nbsp&nbsp- Length 5 ft.<br>&nbsp&nbsp&nbsp- Thickness12 mm' WHERE `item_no`=20023 AND `size`= 'L';
UPDATE `Product_Size` SET `dimension`= '&nbsp&nbsp&nbsp- Weight 12 - 30 lbs<br>&nbsp&nbsp&nbsp- Length 5 ft.<br>&nbsp&nbsp&nbsp- Thickness8 mm' WHERE `item_no`=20023 AND `size`= 'M';
UPDATE `Product_Size` SET `dimension`= '&nbsp&nbsp&nbsp- Weight 5 - 12 lbs<br>&nbsp&nbsp&nbsp- Length5 ft.<br>&nbsp&nbsp&nbsp- Thickness6 mm' WHERE `item_no`=20023 AND `size`= 'S';
UPDATE `Product_Size` SET `dimension`= '&nbsp&nbsp&nbsp- Weight 40+ lbs<br>&nbsp&nbsp&nbsp- Length18 - 26 inches<br>&nbsp&nbsp&nbsp- Thickness1 inch' WHERE `item_no`=20024 AND `size`= 'L';
UPDATE `Product_Size` SET `dimension`= '&nbsp&nbsp&nbsp- Weight 30-40 lbs<br>&nbsp&nbsp&nbsp- Length14 - 20 inches<br>&nbsp&nbsp&nbsp- Thickness5/4 inch' WHERE `item_no`=20024 AND `size`= 'M';
UPDATE `Product_Size` SET `dimension`= '&nbsp&nbsp&nbsp- Weight 14-30 lbs<br>&nbsp&nbsp&nbsp- Length11 - 16 inches<br>&nbsp&nbsp&nbsp- Thickness5/8 inch' WHERE `item_no`=20024 AND `size`= 'S';
UPDATE `Product_Size` SET `dimension`= '&nbsp&nbsp&nbsp- Weight 40+ lbs<br>&nbsp&nbsp&nbsp- Length18 - 26 inches<br>&nbsp&nbsp&nbsp- Thickness1 inch' WHERE `item_no`=20025 AND `size`= 'L';
UPDATE `Product_Size` SET `dimension`= '&nbsp&nbsp&nbsp- Weight 30-40 lbs<br>&nbsp&nbsp&nbsp- Length14 - 20 inches<br>&nbsp&nbsp&nbsp- Thickness5/4 inch' WHERE `item_no`=20025 AND `size`= 'M';
UPDATE `Product_Size` SET `dimension`= '&nbsp&nbsp&nbsp- Weight 14-30 lbs<br>&nbsp&nbsp&nbsp- Length11 - 16 inches<br>&nbsp&nbsp&nbsp- Thickness5/8 inch' WHERE `item_no`=20025 AND `size`= 'S';
UPDATE `Product_Size` SET `dimension`= '&nbsp&nbsp&nbsp- Weight 40+ lbs<br>&nbsp&nbsp&nbsp- Length18 - 26 inches<br>&nbsp&nbsp&nbsp- Thickness1 inch' WHERE `item_no`=20026 AND `size`= 'L';
UPDATE `Product_Size` SET `dimension`= '&nbsp&nbsp&nbsp- Weight 30-40 lbs<br>&nbsp&nbsp&nbsp- Length14 - 20 inches<br>&nbsp&nbsp&nbsp- Thickness5/4 inch' WHERE `item_no`=20026 AND `size`= 'M';
UPDATE `Product_Size` SET `dimension`= '&nbsp&nbsp&nbsp- Weight 14-30 lbs<br>&nbsp&nbsp&nbsp- Length11 - 16 inches<br>&nbsp&nbsp&nbsp- Thickness5/8 inch' WHERE `item_no`=20026 AND `size`= 'S';
UPDATE `Product_Size` SET `dimension`= '&nbsp&nbsp&nbsp- Weight 40+ lbs<br>&nbsp&nbsp&nbsp- Length18 - 26 inches<br>&nbsp&nbsp&nbsp- Thickness1 inch' WHERE `item_no`=20027 AND `size`= 'L';
UPDATE `Product_Size` SET `dimension`= '&nbsp&nbsp&nbsp- Weight 30-40 lbs<br>&nbsp&nbsp&nbsp- Length14 - 20 inches<br>&nbsp&nbsp&nbsp- Thickness5/4 inch' WHERE `item_no`=20027 AND `size`= 'M';
UPDATE `Product_Size` SET `dimension`= '&nbsp&nbsp&nbsp- Weight 14-30 lbs<br>&nbsp&nbsp&nbsp- Length11 - 16 inches<br>&nbsp&nbsp&nbsp- Thickness5/8 inch' WHERE `item_no`=20027 AND `size`= 'S';
UPDATE `Product_Size` SET `dimension`= '&nbsp&nbsp&nbsp- Weight 40+ lbs<br>&nbsp&nbsp&nbsp- Length18 - 26 inches<br>&nbsp&nbsp&nbsp- Thickness1 inch' WHERE `item_no`=20028 AND `size`= 'L';
UPDATE `Product_Size` SET `dimension`= '&nbsp&nbsp&nbsp- Weight 30-40 lbs<br>&nbsp&nbsp&nbsp- Length14 - 20 inches<br>&nbsp&nbsp&nbsp- Thickness5/4 inch' WHERE `item_no`=20028 AND `size`= 'M';
UPDATE `Product_Size` SET `dimension`= '&nbsp&nbsp&nbsp- Weight 14-30 lbs<br>&nbsp&nbsp&nbsp- Length11 - 16 inches<br>&nbsp&nbsp&nbsp- Thickness5/8 inch' WHERE `item_no`=20028 AND `size`= 'S';
UPDATE `Product_Size` SET `dimension`= '&nbsp&nbsp&nbsp- Weight 40+ lbs<br>&nbsp&nbsp&nbsp- Length18 - 26 inches<br>&nbsp&nbsp&nbsp- Thickness1 inch' WHERE `item_no`=20029 AND `size`= 'L';
UPDATE `Product_Size` SET `dimension`= '&nbsp&nbsp&nbsp- Weight 30-40 lbs<br>&nbsp&nbsp&nbsp- Length14 - 20 inches<br>&nbsp&nbsp&nbsp- Thickness5/4 inch' WHERE `item_no`=20029 AND `size`= 'M';
UPDATE `Product_Size` SET `dimension`= '&nbsp&nbsp&nbsp- Weight 14-30 lbs<br>&nbsp&nbsp&nbsp- Length11 - 16 inches<br>&nbsp&nbsp&nbsp- Thickness5/8 inch' WHERE `item_no`=20029 AND `size`= 'S';
UPDATE `Product_Size` SET `dimension`= '&nbsp&nbsp&nbsp- Weight 40+ lbs<br>&nbsp&nbsp&nbsp- Length18 - 26 inches<br>&nbsp&nbsp&nbsp- Thickness1 inch' WHERE `item_no`=20030 AND `size`= 'L';
UPDATE `Product_Size` SET `dimension`= '&nbsp&nbsp&nbsp- Weight 30-40 lbs<br>&nbsp&nbsp&nbsp- Length14 - 20 inches<br>&nbsp&nbsp&nbsp- Thickness5/4 inch' WHERE `item_no`=20030 AND `size`= 'M';
UPDATE `Product_Size` SET `dimension`= '&nbsp&nbsp&nbsp- Weight 14-30 lbs<br>&nbsp&nbsp&nbsp- Length11 - 16 inches<br>&nbsp&nbsp&nbsp- Thickness5/8 inch' WHERE `item_no`=20030 AND `size`= 'S';
UPDATE `Product_Size` SET `dimension`= '&nbsp&nbsp&nbsp- Weight 40+ lbs<br>&nbsp&nbsp&nbsp- Length18 - 26 inches<br>&nbsp&nbsp&nbsp- Thickness1 inch' WHERE `item_no`=20031 AND `size`= 'L';
UPDATE `Product_Size` SET `dimension`= '&nbsp&nbsp&nbsp- Weight 30-40 lbs<br>&nbsp&nbsp&nbsp- Length14 - 20 inches<br>&nbsp&nbsp&nbsp- Thickness5/4 inch' WHERE `item_no`=20031 AND `size`= 'M';
UPDATE `Product_Size` SET `dimension`= '&nbsp&nbsp&nbsp- Weight 14-30 lbs<br>&nbsp&nbsp&nbsp- Length11 - 16 inches<br>&nbsp&nbsp&nbsp- Thickness5/8 inch' WHERE `item_no`=20031 AND `size`= 'S';
UPDATE `Product_Size` SET `dimension`= '&nbsp&nbsp&nbsp- Weight 40+ lbs<br>&nbsp&nbsp&nbsp- Length18 - 26 inches<br>&nbsp&nbsp&nbsp- Thickness1 inch' WHERE `item_no`=20032 AND `size`= 'L';
UPDATE `Product_Size` SET `dimension`= '&nbsp&nbsp&nbsp- Weight 30-40 lbs<br>&nbsp&nbsp&nbsp- Length14 - 20 inches<br>&nbsp&nbsp&nbsp- Thickness5/4 inch' WHERE `item_no`=20032 AND `size`= 'M';
UPDATE `Product_Size` SET `dimension`= '&nbsp&nbsp&nbsp- Weight 14-30 lbs<br>&nbsp&nbsp&nbsp- Length11 - 16 inches<br>&nbsp&nbsp&nbsp- Thickness5/8 inch' WHERE `item_no`=20032 AND `size`= 'S';
UPDATE `Product_Size` SET `dimension`= '&nbsp&nbsp&nbsp- Weight 40+ lbs<br>&nbsp&nbsp&nbsp- Length18 - 26 inches<br>&nbsp&nbsp&nbsp- Thickness1 inch' WHERE `item_no`=20033 AND `size`= 'L';
UPDATE `Product_Size` SET `dimension`= '&nbsp&nbsp&nbsp- Weight 30-40 lbs<br>&nbsp&nbsp&nbsp- Length14 - 20 inches<br>&nbsp&nbsp&nbsp- Thickness5/4 inch' WHERE `item_no`=20033 AND `size`= 'M';
UPDATE `Product_Size` SET `dimension`= '&nbsp&nbsp&nbsp- Weight 14-30 lbs<br>&nbsp&nbsp&nbsp- Length11 - 16 inches<br>&nbsp&nbsp&nbsp- Thickness5/8 inch' WHERE `item_no`=20033 AND `size`= 'S';
UPDATE `Product_Size` SET `dimension`= '&nbsp&nbsp&nbsp- Weight 40+ lbs<br>&nbsp&nbsp&nbsp- Length18 - 26 inches<br>&nbsp&nbsp&nbsp- Thickness1 inch' WHERE `item_no`=20034 AND `size`= 'L';
UPDATE `Product_Size` SET `dimension`= '&nbsp&nbsp&nbsp- Weight 30-40 lbs<br>&nbsp&nbsp&nbsp- Length14 - 20 inches<br>&nbsp&nbsp&nbsp- Thickness5/4 inch' WHERE `item_no`=20034 AND `size`= 'M';
UPDATE `Product_Size` SET `dimension`= '&nbsp&nbsp&nbsp- Weight 14-30 lbs<br>&nbsp&nbsp&nbsp- Length11 - 16 inches<br>&nbsp&nbsp&nbsp- Thickness5/8 inch' WHERE `item_no`=20034 AND `size`= 'S';
UPDATE `Product_Size` SET `dimension`= '&nbsp&nbsp&nbsp- Weight 40+ lbs<br>&nbsp&nbsp&nbsp- Length18 - 26 inches<br>&nbsp&nbsp&nbsp- Thickness1 inch' WHERE `item_no`=20035 AND `size`= 'L';
UPDATE `Product_Size` SET `dimension`= '&nbsp&nbsp&nbsp- Weight 30-40 lbs<br>&nbsp&nbsp&nbsp- Length14 - 20 inches<br>&nbsp&nbsp&nbsp- Thickness5/4 inch' WHERE `item_no`=20035 AND `size`= 'M';
UPDATE `Product_Size` SET `dimension`= '&nbsp&nbsp&nbsp- Weight 14-30 lbs<br>&nbsp&nbsp&nbsp- Length11 - 16 inches<br>&nbsp&nbsp&nbsp- Thickness5/8 inch' WHERE `item_no`=20035 AND `size`= 'S';
UPDATE `Product_Size` SET `dimension`= '&nbsp&nbsp&nbsp- Weight 40+ lbs<br>&nbsp&nbsp&nbsp- Length18 - 26 inches<br>&nbsp&nbsp&nbsp- Thickness1 inch' WHERE `item_no`=20036 AND `size`= 'L';
UPDATE `Product_Size` SET `dimension`= '&nbsp&nbsp&nbsp- Weight 30-40 lbs<br>&nbsp&nbsp&nbsp- Length14 - 20 inches<br>&nbsp&nbsp&nbsp- Thickness5/4 inch' WHERE `item_no`=20036 AND `size`= 'M';
UPDATE `Product_Size` SET `dimension`= '&nbsp&nbsp&nbsp- Weight 14-30 lbs<br>&nbsp&nbsp&nbsp- Length11 - 16 inches<br>&nbsp&nbsp&nbsp- Thickness5/8 inch' WHERE `item_no`=20036 AND `size`= 'S';
UPDATE `Product_Size` SET `dimension`= '&nbsp&nbsp&nbsp- Weight 40+ lbs<br>&nbsp&nbsp&nbsp- Length18 - 26 inches<br>&nbsp&nbsp&nbsp- Thickness1 inch' WHERE `item_no`=20037 AND `size`= 'L';
UPDATE `Product_Size` SET `dimension`= '&nbsp&nbsp&nbsp- Weight 30-40 lbs<br>&nbsp&nbsp&nbsp- Length14 - 20 inches<br>&nbsp&nbsp&nbsp- Thickness5/4 inch' WHERE `item_no`=20037 AND `size`= 'M';
UPDATE `Product_Size` SET `dimension`= '&nbsp&nbsp&nbsp- Weight 14-30 lbs<br>&nbsp&nbsp&nbsp- Length11 - 16 inches<br>&nbsp&nbsp&nbsp- Thickness5/8 inch' WHERE `item_no`=20037 AND `size`= 'S';
UPDATE `Product_Size` SET `dimension`= '&nbsp&nbsp&nbsp- Weight 40+ lbs<br>&nbsp&nbsp&nbsp- Length 4 ft.<br>&nbsp&nbsp&nbsp- Thickness1 inch' WHERE `item_no`=20038 AND `size`= 'L';
UPDATE `Product_Size` SET `dimension`= '&nbsp&nbsp&nbsp- Weight 14-30 lbs<br>&nbsp&nbsp&nbsp- Length4 ft.<br>&nbsp&nbsp&nbsp- Thickness5/8 inch' WHERE `item_no`=20038 AND `size`= 'S';
UPDATE `Product_Size` SET `dimension`= '&nbsp&nbsp&nbsp- Weight 40+ lbs<br>&nbsp&nbsp&nbsp- Length 4 ft.<br>&nbsp&nbsp&nbsp- Thickness1 inch' WHERE `item_no`=20039 AND `size`= 'L';
UPDATE `Product_Size` SET `dimension`= '&nbsp&nbsp&nbsp- Weight 14-30 lbs<br>&nbsp&nbsp&nbsp- Length4 ft.<br>&nbsp&nbsp&nbsp- Thickness5/8 inch' WHERE `item_no`=20039 AND `size`= 'S';
UPDATE `Product_Size` SET `dimension`= '&nbsp&nbsp&nbsp- Weight 40+ lbs<br>&nbsp&nbsp&nbsp- Length 4 ft.<br>&nbsp&nbsp&nbsp- Thickness1 inch' WHERE `item_no`=20040 AND `size`= 'L';
UPDATE `Product_Size` SET `dimension`= '&nbsp&nbsp&nbsp- Weight 14-30 lbs<br>&nbsp&nbsp&nbsp- Length4 ft.<br>&nbsp&nbsp&nbsp- Thickness5/8 inch' WHERE `item_no`=20040 AND `size`= 'S';
UPDATE `Product_Size` SET `dimension`= '&nbsp&nbsp&nbsp- Weight 40+ lbs<br>&nbsp&nbsp&nbsp- Length 4 ft.<br>&nbsp&nbsp&nbsp- Thickness1 inch' WHERE `item_no`=20041 AND `size`= 'L';
UPDATE `Product_Size` SET `dimension`= '&nbsp&nbsp&nbsp- Weight 14-30 lbs<br>&nbsp&nbsp&nbsp- Length4 ft.<br>&nbsp&nbsp&nbsp- Thickness5/8 inch' WHERE `item_no`=20041 AND `size`= 'S';
UPDATE `Product_Size` SET `dimension`= '&nbsp&nbsp&nbsp- Weight 40+ lbs<br>&nbsp&nbsp&nbsp- Length 4 ft.<br>&nbsp&nbsp&nbsp- Thickness1 inch' WHERE `item_no`=20042 AND `size`= 'L';
UPDATE `Product_Size` SET `dimension`= '&nbsp&nbsp&nbsp- Weight 14-30 lbs<br>&nbsp&nbsp&nbsp- Length4 ft.<br>&nbsp&nbsp&nbsp- Thickness5/8 inch' WHERE `item_no`=20042 AND `size`= 'S';
UPDATE `Product_Size` SET `dimension`= '&nbsp&nbsp&nbsp- Weight 40+ lbs<br>&nbsp&nbsp&nbsp- Length 4 ft.<br>&nbsp&nbsp&nbsp- Thickness1 inch' WHERE `item_no`=20043 AND `size`= 'L';
UPDATE `Product_Size` SET `dimension`= '&nbsp&nbsp&nbsp- Weight 14-30 lbs<br>&nbsp&nbsp&nbsp- Length4 ft.<br>&nbsp&nbsp&nbsp- Thickness5/8 inch' WHERE `item_no`=20043 AND `size`= 'S';
UPDATE `Product_Size` SET `dimension`= '&nbsp&nbsp&nbsp- Weight 40+ lbs<br>&nbsp&nbsp&nbsp- Length 4 ft.<br>&nbsp&nbsp&nbsp- Thickness1 inch' WHERE `item_no`=20044 AND `size`= 'L';
UPDATE `Product_Size` SET `dimension`= '&nbsp&nbsp&nbsp- Weight 14-30 lbs<br>&nbsp&nbsp&nbsp- Length4 ft.<br>&nbsp&nbsp&nbsp- Thickness5/8 inch' WHERE `item_no`=20044 AND `size`= 'S';
UPDATE `Product_Size` SET `dimension`= '&nbsp&nbsp&nbsp- Weight 40+ lbs<br>&nbsp&nbsp&nbsp- Length 4 ft.<br>&nbsp&nbsp&nbsp- Thickness1 inch' WHERE `item_no`=20045 AND `size`= 'L';
UPDATE `Product_Size` SET `dimension`= '&nbsp&nbsp&nbsp- Weight 14-30 lbs<br>&nbsp&nbsp&nbsp- Length4 ft.<br>&nbsp&nbsp&nbsp- Thickness5/8 inch' WHERE `item_no`=20045 AND `size`= 'S';
UPDATE `Product_Size` SET `dimension`= '&nbsp&nbsp&nbsp- Weight 40+ lbs<br>&nbsp&nbsp&nbsp- Length 4 ft.<br>&nbsp&nbsp&nbsp- Thickness1 inch' WHERE `item_no`=20046 AND `size`= 'L';
UPDATE `Product_Size` SET `dimension`= '&nbsp&nbsp&nbsp- Weight 14-30 lbs<br>&nbsp&nbsp&nbsp- Length4 ft.<br>&nbsp&nbsp&nbsp- Thickness5/8 inch' WHERE `item_no`=20046 AND `size`= 'S';
UPDATE `Product_Size` SET `dimension`= '&nbsp&nbsp&nbsp- Weight 40+ lbs<br>&nbsp&nbsp&nbsp- Length 4 ft.<br>&nbsp&nbsp&nbsp- Thickness1 inch' WHERE `item_no`=20047 AND `size`= 'L';
UPDATE `Product_Size` SET `dimension`= '&nbsp&nbsp&nbsp- Weight 14-30 lbs<br>&nbsp&nbsp&nbsp- Length4 ft.<br>&nbsp&nbsp&nbsp- Thickness5/8 inch' WHERE `item_no`=20047 AND `size`= 'S';
UPDATE `Product_Size` SET `dimension`= '&nbsp&nbsp&nbsp- Weight 40+ lbs<br>&nbsp&nbsp&nbsp- Length 4 ft.<br>&nbsp&nbsp&nbsp- Thickness1 inch' WHERE `item_no`=20048 AND `size`= 'L';
UPDATE `Product_Size` SET `dimension`= '&nbsp&nbsp&nbsp- Weight 14-30 lbs<br>&nbsp&nbsp&nbsp- Length4 ft.<br>&nbsp&nbsp&nbsp- Thickness5/8 inch' WHERE `item_no`=20048 AND `size`= 'S';
UPDATE `Product_Size` SET `dimension`= '&nbsp&nbsp&nbsp- Weight 40+ lbs<br>&nbsp&nbsp&nbsp- Length 4 ft.<br>&nbsp&nbsp&nbsp- Thickness1 inch' WHERE `item_no`=20049 AND `size`= 'L';
UPDATE `Product_Size` SET `dimension`= '&nbsp&nbsp&nbsp- Weight 14-30 lbs<br>&nbsp&nbsp&nbsp- Length4 ft.<br>&nbsp&nbsp&nbsp- Thickness5/8 inch' WHERE `item_no`=20049 AND `size`= 'S';
UPDATE `Product_Size` SET `dimension`= '&nbsp&nbsp&nbsp- Weight 40+ lbs<br>&nbsp&nbsp&nbsp- Length 4 ft.<br>&nbsp&nbsp&nbsp- Thickness1 inch' WHERE `item_no`=20050 AND `size`= 'L';
UPDATE `Product_Size` SET `dimension`= '&nbsp&nbsp&nbsp- Weight 14-30 lbs<br>&nbsp&nbsp&nbsp- Length4 ft.<br>&nbsp&nbsp&nbsp- Thickness5/8 inch' WHERE `item_no`=20050 AND `size`= 'S';
UPDATE `Product_Size` SET `dimension`= '&nbsp&nbsp&nbsp- Weight 40+ lbs<br>&nbsp&nbsp&nbsp- Length 4 ft.<br>&nbsp&nbsp&nbsp- Thickness1 inch' WHERE `item_no`=20051 AND `size`= 'L';
UPDATE `Product_Size` SET `dimension`= '&nbsp&nbsp&nbsp- Weight 14-30 lbs<br>&nbsp&nbsp&nbsp- Length4 ft.<br>&nbsp&nbsp&nbsp- Thickness5/8 inch' WHERE `item_no`=20051 AND `size`= 'S';
UPDATE `Product_Size` SET `dimension`= '&nbsp&nbsp&nbsp- Weight 40+ lbs<br>&nbsp&nbsp&nbsp- Length 29.5 inches<br>&nbsp&nbsp&nbsp- Thickness1 inch' WHERE `item_no`=20052 AND `size`= 'L';
UPDATE `Product_Size` SET `dimension`= '&nbsp&nbsp&nbsp- Weight 40+ lbs<br>&nbsp&nbsp&nbsp- Length 29.5 inches<br>&nbsp&nbsp&nbsp- Thickness1 inch' WHERE `item_no`=20053 AND `size`= 'L';
UPDATE `Product_Size` SET `dimension`= '&nbsp&nbsp&nbsp- Weight 40+ lbs<br>&nbsp&nbsp&nbsp- Length 29.5 inches<br>&nbsp&nbsp&nbsp- Thickness1 inch' WHERE `item_no`=20054 AND `size`= 'L';
UPDATE `Product_Size` SET `dimension`= '&nbsp&nbsp&nbsp- Weight 40+ lbs<br>&nbsp&nbsp&nbsp- Length 29.5 inches<br>&nbsp&nbsp&nbsp- Thickness1 inch' WHERE `item_no`=20055 AND `size`= 'L';
UPDATE `Product_Size` SET `dimension`= '&nbsp&nbsp&nbsp- Weight 40+ lbs<br>&nbsp&nbsp&nbsp- Length 29.5 inches<br>&nbsp&nbsp&nbsp- Thickness1 inch' WHERE `item_no`=20056 AND `size`= 'L';
UPDATE `Product_Size` SET `dimension`= 'Outer dimensions<br>&nbsp&nbsp&nbsp- 24"L x 19"W x 7"H<br>Inner dimensions<br>&nbsp&nbsp&nbsp- 16"L x 11"W<br>Weight Recommendation<br>&nbsp&nbsp&nbsp- up to 25 lbs' WHERE `item_no`=50002 AND `size`= 'S';
UPDATE `Product_Size` SET `dimension`= 'Outer dimensions<br>&nbsp&nbsp&nbsp- 31"L X 25"W x 8"H<br>Inner dimensions<br>&nbsp&nbsp&nbsp- 21"L x 16"W<br>Weight Recommendation<br>&nbsp&nbsp&nbsp- up to 55 lbs' WHERE `item_no`=50002 AND `size`= 'M';
UPDATE `Product_Size` SET `dimension`= 'Outer dimensions<br>&nbsp&nbsp&nbsp- 24"L x 19"W x 7"H<br>Inner dimensions<br>&nbsp&nbsp&nbsp- 16"L x 11"W<br>Weight Recommendation<br>&nbsp&nbsp&nbsp- up to 25 lbs' WHERE `item_no`=50003 AND `size`= 'S';
UPDATE `Product_Size` SET `dimension`= 'Outer dimensions<br>&nbsp&nbsp&nbsp- 31"L X 25"W x 8"H<br>Inner dimensions<br>&nbsp&nbsp&nbsp- 21"L x 16"W<br>Weight Recommendation<br>&nbsp&nbsp&nbsp- up to 55 lbs' WHERE `item_no`=50003 AND `size`= 'M';
UPDATE `Product_Size` SET `dimension`= 'Outer dimensions<br>&nbsp&nbsp&nbsp- 24"L x 19"W x 7"H<br>Inner dimensions<br>&nbsp&nbsp&nbsp- 16"L x 11"W<br>Weight Recommendation<br>&nbsp&nbsp&nbsp- up to 25 lbs' WHERE `item_no`=50004 AND `size`= 'S';
UPDATE `Product_Size` SET `dimension`= 'Outer dimensions<br>&nbsp&nbsp&nbsp- 31"L X 25"W x 8"H<br>Inner dimensions<br>&nbsp&nbsp&nbsp- 21"L x 16"W<br>Weight Recommendation<br>&nbsp&nbsp&nbsp- up to 55 lbs' WHERE `item_no`=50004 AND `size`= 'M';
UPDATE `Product_Size` SET `dimension`= 'Outer dimensions<br>&nbsp&nbsp&nbsp- 24"L x 19"W x 7"H<br>Inner dimensions<br>&nbsp&nbsp&nbsp- 16"L x 11"W<br>Weight Recommendation<br>&nbsp&nbsp&nbsp- up to 25 lbs' WHERE `item_no`=50005 AND `size`= 'S';
UPDATE `Product_Size` SET `dimension`= 'Outer dimensions<br>&nbsp&nbsp&nbsp- 31"L X 25"W x 8"H<br>Inner dimensions<br>&nbsp&nbsp&nbsp- 21"L x 16"W<br>Weight Recommendation<br>&nbsp&nbsp&nbsp- up to 55 lbs' WHERE `item_no`=50005 AND `size`= 'M';
UPDATE `Product_Size` SET `dimension`= 'Cup Diameter<br>&nbsp&nbsp&nbsp- 13"<br>Flat Dimensions<br>&nbsp&nbsp&nbsp- 16"x 18"<br>Weight Recommendation<br>&nbsp&nbsp&nbsp- up to 12 lbs' WHERE `item_no`=50010 AND `size`= 'S';
UPDATE `Product_Size` SET `dimension`= 'Cup Diameter<br>&nbsp&nbsp&nbsp- 18"<br>Flat Dimensions<br>&nbsp&nbsp&nbsp- 23"x 25"<br>Weight Recommendation<br>&nbsp&nbsp&nbsp- up to 30 lbs' WHERE `item_no`=50010 AND `size`= 'L';
UPDATE `Product_Size` SET `dimension`= 'Cup Diameter<br>&nbsp&nbsp&nbsp- 13"<br>Flat Dimensions<br>&nbsp&nbsp&nbsp- 16"x 18"<br>Weight Recommendation<br>&nbsp&nbsp&nbsp- up to 12 lbs' WHERE `item_no`=50011 AND `size`= 'S';
UPDATE `Product_Size` SET `dimension`= 'Cup Diameter<br>&nbsp&nbsp&nbsp- 18"<br>Flat Dimensions<br>&nbsp&nbsp&nbsp- 23"x 25"<br>Weight Recommendation<br>&nbsp&nbsp&nbsp- up to 30 lbs' WHERE `item_no`=50011 AND `size`= 'L';
UPDATE `Product_Size` SET `dimension`= 'Cup Diameter<br>&nbsp&nbsp&nbsp- 13"<br>Flat Dimensions<br>&nbsp&nbsp&nbsp- 16"x 18"<br>Weight Recommendation<br>&nbsp&nbsp&nbsp- up to 12 lbs' WHERE `item_no`=50012 AND `size`= 'S';
UPDATE `Product_Size` SET `dimension`= 'Cup Diameter<br>&nbsp&nbsp&nbsp- 18"<br>Flat Dimensions<br>&nbsp&nbsp&nbsp- 23"x 25"<br>Weight Recommendation<br>&nbsp&nbsp&nbsp- up to 30 lbs' WHERE `item_no`=50012 AND `size`= 'L';
UPDATE `Product_Size` SET `dimension`= 'Outer dimensions<br>&nbsp&nbsp&nbsp- 24"L x 19"W x 7"H<br>Inner dimensions<br>&nbsp&nbsp&nbsp- 16"L x 11"W<br>Weight Recommendation<br>&nbsp&nbsp&nbsp- up to 25 lbs' WHERE `item_no`=50001 AND `size`= 'S';
UPDATE `Product_Size` SET `dimension`= 'Outer dimensions<br>&nbsp&nbsp&nbsp- 31"L X 25"W x 8"H<br>Inner dimensions<br>&nbsp&nbsp&nbsp- 21"L x 16"W<br>Weight Recommendation<br>&nbsp&nbsp&nbsp- up to 55 lbs' WHERE `item_no`=50001 AND `size`= 'M';
