UPDATE Product_Size SET dimension='- 12W x 12D x 6.5H inches<br>- Weight - 10lbs<br>- Holds up to 5.5 cups of dry food or 44 oz of water.' WHERE item_no=10001 and size='L';
UPDATE Product_Size SET dimension='- 10W x 10D x 5H inches<br>- Weight - 4lbs<br>- Holds up to 4.5 cups of dry food or 36 oz of water.' WHERE item_no=10001 and size='M';
UPDATE Product_Size SET dimension='- 8W x 8D x 3H inches<br>- Weight - 2lbs<br>- Holds up to 2 cups of dry food or 16 oz of water.' WHERE item_no=10001 and size='S';
UPDATE Product_Size SET dimension='- 9.25W x 9.25D x 4.25H inches<br>- Weight - 5lbs<br>- Holds up to 5.5 cups of dry food or 44 oz of water' WHERE item_no=10002 and size='L';
UPDATE Product_Size SET dimension='- 8W x 8D x 4H inches<br>- Weight - 4lbs<br>- Holds up to 4.5 cups of dry food or 36 oz of water.' WHERE item_no=10002 and size='M';
UPDATE Product_Size SET dimension='- 6.50W x 6.50D x 3H inches<br>- Weight - 1lbs<br>- Holds up to 2 cups of dry food or 16 oz of water' WHERE item_no=10002 and size='S';
UPDATE Product_Size SET dimension='- 14.50W x 8D x 5H inches<br>- Weight - 2lbs<br>- Holds up to 2 cups of dry food or 16 oz of water.' WHERE item_no=10003 and size='S';
UPDATE Product_Size SET dimension='- 7.50W x 7.50D x 4.50H inches<br>- Weight - 2lbs<br>- Holds up to 2 cups of dry food or 16 oz of water.' WHERE item_no=10004 and size='S';
UPDATE Product_Size SET dimension='- 7.50W x 7.50D x 4.50H inches<br>- Weight - 2lbs<br>- Holds up to 2 cups of dry food or 16 oz of water.' WHERE item_no=10005 and size='S';
UPDATE Product_Size SET dimension='- 8.75W x 8.75D x 3.75H inches<br>- Weight - 2.5lbs<br>- Holds up to 5.5 cups of dry food or 44 oz of water.' WHERE item_no=10006 and size='L';
UPDATE Product_Size SET dimension='- 8W x 8D x 3.25H inches<br>- Weight - 2lbs<br>- Holds up to 4.5 cups of dry food or 36 oz of water.' WHERE item_no=10006 and size='M';
UPDATE Product_Size SET dimension='- 6.5W x 6.5D x 3H inches<br>- Weight - 1lbs<br>- Holds up to 2 cups of dry food or 16 oz of water.' WHERE item_no=10006 and size='S';
UPDATE Product_Size SET dimension='- 10.5W x 10.5D x 4H inches<br>- Weight - 4lbs<br>- Holds up to 5.5 cups of dry food or 44 oz of water.' WHERE item_no=10007 and size='L';
UPDATE Product_Size SET dimension='- 10W x 10D x 3.5H inches<br>- Weight - 3lbs<br>- Holds up to 4.5 cups of dry food or 36 oz of water.' WHERE item_no=10007 and size='M';
UPDATE Product_Size SET dimension='- 8.5W x 8.5D x 2.75H inches<br>- Weight - 2lbs<br>- Holds up to 2 cups of dry food or 16 oz of water.' WHERE item_no=10007 and size='S';
UPDATE Product_Size SET dimension='- 7.25W x 7.25D x 4.5H inches<br>- Weight - 4lbs<br>- Holds up to 2 cups of dry food or 16 oz of water.' WHERE item_no=10008 and size='S';
UPDATE Product_Size SET dimension='- 10W x 10D x 12H inches<br>- Weight - 12lbs<br>- Holds up to 5.5 cups of dry food or 44 oz of water.' WHERE item_no=10009 and size='L';
UPDATE Product_Size SET dimension='- 9W x 9D x 9H inches<br>- Weight - 8lbs<br>- Holds up to 4.5 cups of dry food or 36 oz of water.' WHERE item_no=10009 and size='M';
UPDATE Product_Size SET dimension='- 8W x 8D x 4H inches<br>- Weight - 3lbs<br>- Holds up to 2 cups of dry food or 16 oz of water.' WHERE item_no=10009 and size='S';
UPDATE Product_Size SET dimension='- 10W x 10D x 12H inches<br>- Weight - 12lbs<br>- Holds up to 5.5 cups of dry food or 44 oz of water.' WHERE item_no=10010 and size='L';
UPDATE Product_Size SET dimension='- 9W x 9D x 9H inches<br>- Weight - 8lbs<br>- Holds up to 4.5 cups of dry food or 36 oz of water.' WHERE item_no=10010 and size='M';
UPDATE Product_Size SET dimension='- 8W x 8D x 4H inches<br>- Weight - 3lbs<br>- Holds up to 2 cups of dry food or 16 oz of water.' WHERE item_no=10010 and size='S';
UPDATE Product_Size SET dimension='- 15.75W x 8D x 4H inches<br>- Weight - 3lbs<br>- Holds up to 4.5 cups of dry food or 36 oz of water.' WHERE item_no=10011 and size='M';
UPDATE Product_Size SET dimension='- 12.5W x 8.5D x 4H inches<br>- Weight - 2lbs<br>- Holds up to 2 cups of dry food or 16 oz of water.' WHERE item_no=10011 and size='S';
UPDATE Product_Size SET dimension='- 7W x 2D x 3H inches<br>- Weight - 4lbs<br>- Holds up to 2.5 cups of dry food or 16 oz of water.' WHERE item_no=10012 and size='M';
UPDATE Product_Size SET dimension='- 5W x 1.5D x 2.5H inches<br>- Weight - 2lbs<br>- Holds up to 1.5 cups of dry food or 12 oz of water.' WHERE item_no=10012 and size='S';
UPDATE Product_Size SET dimension='- 7W x 2D x 3H inches<br>- Weight - 4lbs<br>- Holds up to 2.5 cups of dry food or 16 oz of water.' WHERE item_no=10013 and size='M';
UPDATE Product_Size SET dimension='- 5W x 1.5D x 2.5H inches<br>- Weight - 2lbs<br>- Holds up to 1.5 cups of dry food or 12 oz of water.' WHERE item_no=10013 and size='S';

UPDATE Product_Size SET dimension='- Weight 40+ lbs<br>- Length 19–22.5 inch<br>- Thickness  1 inch' WHERE item_no=20001 and size='XL';
UPDATE Product_Size SET dimension='- Weight 30–40 lbs<br>- Length 15–18 inch<br>- Thickness  7/8 inch' WHERE item_no=20001 and size='L';
UPDATE Product_Size SET dimension='- Weight 12–30 lbs<br>- Length  12.5–15  inch<br>- Thickness  5/8 inch' WHERE item_no=20001 and size='M';
UPDATE Product_Size SET dimension='- Weight 5–12 lbs<br>- Length 10–13 inch<br>- Thickness  1/2  inch' WHERE item_no=20001 and size='S';
UPDATE Product_Size SET dimension='- Weight 40+ lbs<br>- Length 19–22.5 inch<br>- Thickness  1 inch' WHERE item_no=20002 and size='XL';
UPDATE Product_Size SET dimension='- Weight 30–40 lbs<br>- Length 15–18 inch<br>- Thickness  7/8 inch' WHERE item_no=20002 and size='L';
UPDATE Product_Size SET dimension='- Weight 12–30 lbs<br>- Length  12.5–15  inch<br>- Thickness  5/8 inch' WHERE item_no=20002 and size='M';
UPDATE Product_Size SET dimension='- Weight 5–12 lbs<br>- Length 10–13 inch<br>- Thickness  1/2  inch' WHERE item_no=20002 and size='S';
UPDATE Product_Size SET dimension='- Weight 40+ lbs<br>- Length 19–22.5 inch<br>- Thickness  1 inch' WHERE item_no=20003 and size='XL';
UPDATE Product_Size SET dimension='- Weight 30–40 lbs<br>- Length 15–18 inch<br>- Thickness  7/8 inch' WHERE item_no=20003 and size='L';
UPDATE Product_Size SET dimension='- Weight 12–30 lbs<br>- Length  12.5–15  inch<br>- Thickness  5/8 inch' WHERE item_no=20003 and size='M';
UPDATE Product_Size SET dimension='- Weight 5–12 lbs<br>- Length 10–13 inch<br>- Thickness  1/2  inch' WHERE item_no=20003 and size='S';
UPDATE Product_Size SET dimension='- Weight 40+ lbs<br>- Length 19–22.5 inch<br>- Thickness  1 inch' WHERE item_no=20004 and size='XL';
UPDATE Product_Size SET dimension='- Weight 30–40 lbs<br>- Length 15–18 inch<br>- Thickness  7/8 inch' WHERE item_no=20004 and size='L';
UPDATE Product_Size SET dimension='- Weight 12–30 lbs<br>- Length  12.5–15  inch<br>- Thickness  5/8 inch' WHERE item_no=20004 and size='M';
UPDATE Product_Size SET dimension='- Weight 5–12 lbs<br>- Length 10–13 inch<br>- Thickness  1/2  inch' WHERE item_no=20004 and size='S';
UPDATE Product_Size SET dimension='- Weight 40+ lbs<br>- Length 19–22.5 inch<br>- Thickness  1 inch' WHERE item_no=20005 and size='XL';
UPDATE Product_Size SET dimension='- Weight 30–40 lbs<br>- Length 15–18 inch<br>- Thickness  7/8 inch' WHERE item_no=20005 and size='L';
UPDATE Product_Size SET dimension='- Weight 12–30 lbs<br>- Length  12.5–15  inch<br>- Thickness  5/8 inch' WHERE item_no=20005 and size='M';
UPDATE Product_Size SET dimension='- Weight 5–12 lbs<br>- Length 10–13 inch<br>- Thickness  1/2  inch' WHERE item_no=20005 and size='S';
UPDATE Product_Size SET dimension='- Weight 40+ lbs<br>- Length 19–22.5 inch<br>- Thickness  1 inch' WHERE item_no=20006 and size='XL';
UPDATE Product_Size SET dimension='- Weight 30–40 lbs<br>- Length 15–18 inch<br>- Thickness  7/8 inch' WHERE item_no=20006 and size='L';
UPDATE Product_Size SET dimension='- Weight 12–30 lbs<br>- Length  12.5–15  inch<br>- Thickness  5/8 inch' WHERE item_no=20006 and size='M';
UPDATE Product_Size SET dimension='- Weight 5–12 lbs<br>- Length 10–13 inch<br>- Thickness  1/2  inch' WHERE item_no=20006 and size='S';
UPDATE Product_Size SET dimension='- Weight 40+ lbs<br>- Length 19–27 inch<br>- Thickness  1 inch' WHERE item_no=20007 and size='XL';
UPDATE Product_Size SET dimension='- Weight 30–40 lbs<br>- Length 13.5–18.5 inch<br>- Thickness  7/8 inch' WHERE item_no=20007 and size='L';
UPDATE Product_Size SET dimension='- Weight 12–30 lbs<br>- Length  10.5–13.5  inch<br>- Thickness  5/8 inch' WHERE item_no=20007 and size='M';
UPDATE Product_Size SET dimension='- Weight 5–12 lbs<br>- Length 9–12  inch<br>- Thickness  1/2  inch' WHERE item_no=20007 and size='S';
UPDATE Product_Size SET dimension='- Weight 40+ lbs<br>- Length 19–22.5 inch<br>- Thickness  1 inch' WHERE item_no=20008 and size='XL';
UPDATE Product_Size SET dimension='- Weight 30–40 lbs<br>- Length 15–18 inch<br>- Thickness  7/8 inch' WHERE item_no=20008 and size='L';
UPDATE Product_Size SET dimension='- Weight 12–30 lbs<br>- Length  12.5–15  inch<br>- Thickness  5/8 inch' WHERE item_no=20008 and size='M';
UPDATE Product_Size SET dimension='- Weight 5–12 lbs<br>- Length 10–13 inch<br>- Thickness  1/2  inch' WHERE item_no=20008 and size='S';
UPDATE Product_Size SET dimension='- Weight 40+ lbs<br>- Length 19–22.5 inch<br>- Thickness  1 inch' WHERE item_no=20008 and size='XL';
UPDATE Product_Size SET dimension='- Weight 30–40 lbs<br>- Length 15–18 inch<br>- Thickness  7/8 inch' WHERE item_no=20009 and size='L';
UPDATE Product_Size SET dimension='- Weight 12–30 lbs<br>- Length  12.5–15  inch<br>- Thickness  5/8 inch' WHERE item_no=20009 and size='M';
UPDATE Product_Size SET dimension='- Weight 5–12 lbs<br>- Length 10–13 inch<br>- Thickness  1/2  inch' WHERE item_no=20009 and size='S';
UPDATE Product_Size SET dimension='- Weight 40+ lbs<br>- Length 19–22.5 inch<br>- Thickness  1 inch' WHERE item_no=20010 and size='XL';
UPDATE Product_Size SET dimension='- Weight 30–40 lbs<br>- Length 15–18 inch<br>- Thickness  7/8 inch' WHERE item_no=20010 and size='L';
UPDATE Product_Size SET dimension='- Weight 12–30 lbs<br>- Length  12.5–15  inch<br>- Thickness  5/8 inch' WHERE item_no=20010 and size='M';
UPDATE Product_Size SET dimension='- Weight 5–12 lbs<br>- Length 10–13 inch<br>- Thickness  1/2  inch' WHERE item_no=20010 and size='S';
UPDATE Product_Size SET dimension='- Weight 35+ lbs<br>- Length 7 ft.<br>- Thickness  12 mm' WHERE item_no=20011 and size='L';
UPDATE Product_Size SET dimension='- Weight 12 - 30 lbs<br>- Length 7 ft.<br>- Thickness  8 mm' WHERE item_no=20011 and size='M';
UPDATE Product_Size SET dimension='- Weight 5 - 12 lbs<br>- Length  7 ft.<br>- Thickness  6 mm' WHERE item_no=20011 and size='S';
UPDATE Product_Size SET dimension='- Weight 35+ lbs<br>- Length 7 ft.<br>- Thickness  12 mm' WHERE item_no=20012 and size='L';
UPDATE Product_Size SET dimension='- Weight 12 - 30 lbs<br>- Length 7 ft.<br>- Thickness  8 mm' WHERE item_no=20012 and size='M';
UPDATE Product_Size SET dimension='- Weight 5 - 12 lbs<br>- Length  7 ft.<br>- Thickness  6 mm' WHERE item_no=20012 and size='S';
UPDATE Product_Size SET dimension='- Weight 35+ lbs<br>- Length 7 ft.<br>- Thickness  12 mm' WHERE item_no=20013 and size='L';
UPDATE Product_Size SET dimension='- Weight 12 - 30 lbs<br>- Length 7 ft.<br>- Thickness  8 mm' WHERE item_no=20013 and size='M';
UPDATE Product_Size SET dimension='- Weight 5 - 12 lbs<br>- Length  7 ft.<br>- Thickness  6 mm' WHERE item_no=20013 and size='S';
UPDATE Product_Size SET dimension='- Weight 35+ lbs<br>- Length 7 ft.<br>- Thickness  12 mm' WHERE item_no=20014 and size='L';
UPDATE Product_Size SET dimension='- Weight 12 - 30 lbs<br>- Length 7 ft.<br>- Thickness  8 mm' WHERE item_no=20014 and size='M';
UPDATE Product_Size SET dimension='- Weight 5 - 12 lbs<br>- Length  7 ft.<br>- Thickness  6 mm' WHERE item_no=20014 and size='S';
UPDATE Product_Size SET dimension='- Weight 35+ lbs<br>- Length 7 ft.<br>- Thickness  12 mm' WHERE item_no=20015 and size='L';
UPDATE Product_Size SET dimension='- Weight 12 - 30 lbs<br>- Length 7 ft.<br>- Thickness  8 mm' WHERE item_no=20015 and size='M';
UPDATE Product_Size SET dimension='- Weight 5 - 12 lbs<br>- Length  7 ft.<br>- Thickness  6 mm' WHERE item_no=20015 and size='S';
UPDATE Product_Size SET dimension='- Weight 35+ lbs<br>- Length 7 ft.<br>- Thickness  12 mm' WHERE item_no=20016 and size='L';
UPDATE Product_Size SET dimension='- Weight 12 - 30 lbs<br>- Length 7 ft.<br>- Thickness  8 mm' WHERE item_no=20016 and size='M';
UPDATE Product_Size SET dimension='- Weight 5 - 12 lbs<br>- Length  7 ft.<br>- Thickness  6 mm' WHERE item_no=20016 and size='S';
UPDATE Product_Size SET dimension='- Weight 35+ lbs<br>- Length 7 ft.<br>- Thickness  12 mm' WHERE item_no=20017 and size='L';
UPDATE Product_Size SET dimension='- Weight 12 - 30 lbs<br>- Length 7 ft.<br>- Thickness  8 mm' WHERE item_no=20017 and size='M';
UPDATE Product_Size SET dimension='- Weight 5 - 12 lbs<br>- Length  7 ft.<br>- Thickness  6 mm' WHERE item_no=20017 and size='S';
UPDATE Product_Size SET dimension='- Weight 35+ lbs<br>- Length 7 ft.<br>- Thickness  12 mm' WHERE item_no=20018 and size='L';
UPDATE Product_Size SET dimension='- Weight 12 - 30 lbs<br>- Length 7 ft.<br>- Thickness  8 mm' WHERE item_no=20018 and size='M';
UPDATE Product_Size SET dimension='- Weight 5 - 12 lbs<br>- Length  7 ft.<br>- Thickness  6 mm' WHERE item_no=20018 and size='S';
UPDATE Product_Size SET dimension='- Weight 35+ lbs<br>- Length 7 ft.<br>- Thickness12 mm' WHERE item_no=20019 and size='L';
UPDATE Product_Size SET dimension='- Weight 12 - 30 lbs<br>- Length 7 ft.<br>- Thickness8 mm' WHERE item_no=20019 and size='M';
UPDATE Product_Size SET dimension='- Weight 5 - 12 lbs<br>- Length7 ft.<br>- Thickness6 mm' WHERE item_no=20019 and size='S';
UPDATE Product_Size SET dimension='- Weight 35+ lbs<br>- Length 7 ft.<br>- Thickness12 mm' WHERE item_no=20020 and size='L';
UPDATE Product_Size SET dimension='- Weight 12 - 30 lbs<br>- Length 7 ft.<br>- Thickness8 mm' WHERE item_no=20020 and size='M';
UPDATE Product_Size SET dimension='- Weight 5 - 12 lbs<br>- Length7 ft.<br>- Thickness6 mm' WHERE item_no=20020 and size='S';
UPDATE Product_Size SET dimension='- Weight 35+ lbs<br>- Length 5 ft.<br>- Thickness12 mm' WHERE item_no=20021 and size='L';
UPDATE Product_Size SET dimension='- Weight 12 - 30 lbs<br>- Length 5 ft.<br>- Thickness8 mm' WHERE item_no=20021 and size='M';
UPDATE Product_Size SET dimension='- Weight 5 - 12 lbs<br>- Length5 ft.<br>- Thickness6 mm' WHERE item_no=20021 and size='S';
UPDATE Product_Size SET dimension='- Weight 35+ lbs<br>- Length 5 ft.<br>- Thickness12 mm' WHERE item_no=20022 and size='L';
UPDATE Product_Size SET dimension='- Weight 12 - 30 lbs<br>- Length 5 ft.<br>- Thickness8 mm' WHERE item_no=20022 and size='M';
UPDATE Product_Size SET dimension='- Weight 5 - 12 lbs<br>- Length5 ft.<br>- Thickness6 mm' WHERE item_no=20022 and size='S';
UPDATE Product_Size SET dimension='- Weight 35+ lbs<br>- Length 5 ft.<br>- Thickness12 mm' WHERE item_no=20023 and size='L';
UPDATE Product_Size SET dimension='- Weight 12 - 30 lbs<br>- Length 5 ft.<br>- Thickness8 mm' WHERE item_no=20023 and size='M';
UPDATE Product_Size SET dimension='- Weight 5 - 12 lbs<br>- Length5 ft.<br>- Thickness6 mm' WHERE item_no=20023 and size='S';
UPDATE Product_Size SET dimension='- Weight 40+ lbs<br>- Length18 - 26 inches<br>- Thickness1 inch' WHERE item_no=20024 and size='L';
UPDATE Product_Size SET dimension='- Weight 30–40 lbs<br>- Length14 - 20 inches<br>- Thickness5/4 inch' WHERE item_no=20024 and size='M';
UPDATE Product_Size SET dimension='- Weight 14–30 lbs<br>- Length11 - 16 inches<br>- Thickness5/8 inch' WHERE item_no=20024 and size='S';
UPDATE Product_Size SET dimension='- Weight 40+ lbs<br>- Length18 - 26 inches<br>- Thickness1 inch' WHERE item_no=20025 and size='L';
UPDATE Product_Size SET dimension='- Weight 30–40 lbs<br>- Length14 - 20 inches<br>- Thickness5/4 inch' WHERE item_no=20025 and size='M';
UPDATE Product_Size SET dimension='- Weight 14–30 lbs<br>- Length11 - 16 inches<br>- Thickness5/8 inch' WHERE item_no=20025 and size='S';
UPDATE Product_Size SET dimension='- Weight 40+ lbs<br>- Length18 - 26 inches<br>- Thickness1 inch' WHERE item_no=20026 and size='L';
UPDATE Product_Size SET dimension='- Weight 30–40 lbs<br>- Length14 - 20 inches<br>- Thickness5/4 inch' WHERE item_no=20026 and size='M';
UPDATE Product_Size SET dimension='- Weight 14–30 lbs<br>- Length11 - 16 inches<br>- Thickness5/8 inch' WHERE item_no=20026 and size='S';
UPDATE Product_Size SET dimension='- Weight 40+ lbs<br>- Length18 - 26 inches<br>- Thickness1 inch' WHERE item_no=20027 and size='L';
UPDATE Product_Size SET dimension='- Weight 30–40 lbs<br>- Length14 - 20 inches<br>- Thickness5/4 inch' WHERE item_no=20027 and size='M';
UPDATE Product_Size SET dimension='- Weight 14–30 lbs<br>- Length11 - 16 inches<br>- Thickness5/8 inch' WHERE item_no=20027 and size='S';
UPDATE Product_Size SET dimension='- Weight 40+ lbs<br>- Length18 - 26 inches<br>- Thickness1 inch' WHERE item_no=20028 and size='L';
UPDATE Product_Size SET dimension='- Weight 30–40 lbs<br>- Length14 - 20 inches<br>- Thickness5/4 inch' WHERE item_no=20028 and size='M';
UPDATE Product_Size SET dimension='- Weight 14–30 lbs<br>- Length11 - 16 inches<br>- Thickness5/8 inch' WHERE item_no=20028 and size='S';
UPDATE Product_Size SET dimension='- Weight 40+ lbs<br>- Length18 - 26 inches<br>- Thickness1 inch' WHERE item_no=20029 and size='L';
UPDATE Product_Size SET dimension='- Weight 30–40 lbs<br>- Length14 - 20 inches<br>- Thickness5/4 inch' WHERE item_no=20029 and size='M';
UPDATE Product_Size SET dimension='- Weight 14–30 lbs<br>- Length11 - 16 inches<br>- Thickness5/8 inch' WHERE item_no=20029 and size='S';
UPDATE Product_Size SET dimension='- Weight 40+ lbs<br>- Length18 - 26 inches<br>- Thickness1 inch' WHERE item_no=20030 and size='L';
UPDATE Product_Size SET dimension='- Weight 30–40 lbs<br>- Length14 - 20 inches<br>- Thickness5/4 inch' WHERE item_no=20030 and size='M';
UPDATE Product_Size SET dimension='- Weight 14–30 lbs<br>- Length11 - 16 inches<br>- Thickness5/8 inch' WHERE item_no=20030 and size='S';
UPDATE Product_Size SET dimension='- Weight 40+ lbs<br>- Length18 - 26 inches<br>- Thickness1 inch' WHERE item_no=20031 and size='L';
UPDATE Product_Size SET dimension='- Weight 30–40 lbs<br>- Length14 - 20 inches<br>- Thickness5/4 inch' WHERE item_no=20031 and size='M';
UPDATE Product_Size SET dimension='- Weight 14–30 lbs<br>- Length11 - 16 inches<br>- Thickness5/8 inch' WHERE item_no=20031 and size='S';
UPDATE Product_Size SET dimension='- Weight 40+ lbs<br>- Length18 - 26 inches<br>- Thickness1 inch' WHERE item_no=20032 and size='L';
UPDATE Product_Size SET dimension='- Weight 30–40 lbs<br>- Length14 - 20 inches<br>- Thickness5/4 inch' WHERE item_no=20032 and size='M';
UPDATE Product_Size SET dimension='- Weight 14–30 lbs<br>- Length11 - 16 inches<br>- Thickness5/8 inch' WHERE item_no=20032 and size='S';
UPDATE Product_Size SET dimension='- Weight 40+ lbs<br>- Length18 - 26 inches<br>- Thickness1 inch' WHERE item_no=20033 and size='L';
UPDATE Product_Size SET dimension='- Weight 30–40 lbs<br>- Length14 - 20 inches<br>- Thickness5/4 inch' WHERE item_no=20033 and size='M';
UPDATE Product_Size SET dimension='- Weight 14–30 lbs<br>- Length11 - 16 inches<br>- Thickness5/8 inch' WHERE item_no=20033 and size='S';
UPDATE Product_Size SET dimension='- Weight 40+ lbs<br>- Length18 - 26 inches<br>- Thickness1 inch' WHERE item_no=20034 and size='L';
UPDATE Product_Size SET dimension='- Weight 30–40 lbs<br>- Length14 - 20 inches<br>- Thickness5/4 inch' WHERE item_no=20034 and size='M';
UPDATE Product_Size SET dimension='- Weight 14–30 lbs<br>- Length11 - 16 inches<br>- Thickness5/8 inch' WHERE item_no=20034 and size='S';
UPDATE Product_Size SET dimension='- Weight 40+ lbs<br>- Length18 - 26 inches<br>- Thickness1 inch' WHERE item_no=20035 and size='L';
UPDATE Product_Size SET dimension='- Weight 30–40 lbs<br>- Length14 - 20 inches<br>- Thickness5/4 inch' WHERE item_no=20035 and size='M';
UPDATE Product_Size SET dimension='- Weight 14–30 lbs<br>- Length11 - 16 inches<br>- Thickness5/8 inch' WHERE item_no=20035 and size='S';
UPDATE Product_Size SET dimension='- Weight 40+ lbs<br>- Length18 - 26 inches<br>- Thickness1 inch' WHERE item_no=20036 and size='L';
UPDATE Product_Size SET dimension='- Weight 30–40 lbs<br>- Length14 - 20 inches<br>- Thickness5/4 inch' WHERE item_no=20036 and size='M';
UPDATE Product_Size SET dimension='- Weight 14–30 lbs<br>- Length11 - 16 inches<br>- Thickness5/8 inch' WHERE item_no=20036 and size='S';
UPDATE Product_Size SET dimension='- Weight 40+ lbs<br>- Length18 - 26 inches<br>- Thickness1 inch' WHERE item_no=20037 and size='L';
UPDATE Product_Size SET dimension='- Weight 30–40 lbs<br>- Length14 - 20 inches<br>- Thickness5/4 inch' WHERE item_no=20037 and size='M';
UPDATE Product_Size SET dimension='- Weight 14–30 lbs<br>- Length11 - 16 inches<br>- Thickness5/8 inch' WHERE item_no=20037 and size='S';
UPDATE Product_Size SET dimension='- Weight 40+ lbs<br>- Length 4 ft.<br>- Thickness1 inch' WHERE item_no=20038 and size='L';
UPDATE Product_Size SET dimension='- Weight 14–30 lbs<br>- Length4 ft.<br>- Thickness5/8 inch' WHERE item_no=20038 and size='S';
UPDATE Product_Size SET dimension='- Weight 40+ lbs<br>- Length 4 ft.<br>- Thickness1 inch' WHERE item_no=20039 and size='L';
UPDATE Product_Size SET dimension='- Weight 14–30 lbs<br>- Length4 ft.<br>- Thickness5/8 inch' WHERE item_no=20039 and size='S';
UPDATE Product_Size SET dimension='- Weight 40+ lbs<br>- Length 4 ft.<br>- Thickness1 inch' WHERE item_no=20040 and size='L';
UPDATE Product_Size SET dimension='- Weight 14–30 lbs<br>- Length4 ft.<br>- Thickness5/8 inch' WHERE item_no=20040 and size='S';
UPDATE Product_Size SET dimension='- Weight 40+ lbs<br>- Length 4 ft.<br>- Thickness1 inch' WHERE item_no=20041 and size='L';
UPDATE Product_Size SET dimension='- Weight 14–30 lbs<br>- Length4 ft.<br>- Thickness5/8 inch' WHERE item_no=20041 and size='S';
UPDATE Product_Size SET dimension='- Weight 40+ lbs<br>- Length 4 ft.<br>- Thickness1 inch' WHERE item_no=20042 and size='L';
UPDATE Product_Size SET dimension='- Weight 14–30 lbs<br>- Length4 ft.<br>- Thickness5/8 inch' WHERE item_no=20042 and size='S';
UPDATE Product_Size SET dimension='- Weight 40+ lbs<br>- Length 4 ft.<br>- Thickness1 inch' WHERE item_no=20043 and size='L';
UPDATE Product_Size SET dimension='- Weight 14–30 lbs<br>- Length4 ft.<br>- Thickness5/8 inch' WHERE item_no=20043 and size='S';
UPDATE Product_Size SET dimension='- Weight 40+ lbs<br>- Length 4 ft.<br>- Thickness1 inch' WHERE item_no=20044 and size='L';
UPDATE Product_Size SET dimension='- Weight 14–30 lbs<br>- Length4 ft.<br>- Thickness5/8 inch' WHERE item_no=20044 and size='S';
UPDATE Product_Size SET dimension='- Weight 40+ lbs<br>- Length 4 ft.<br>- Thickness1 inch' WHERE item_no=20045 and size='L';
UPDATE Product_Size SET dimension='- Weight 14–30 lbs<br>- Length4 ft.<br>- Thickness5/8 inch' WHERE item_no=20045 and size='S';
UPDATE Product_Size SET dimension='- Weight 40+ lbs<br>- Length 4 ft.<br>- Thickness1 inch' WHERE item_no=20046 and size='L';
UPDATE Product_Size SET dimension='- Weight 14–30 lbs<br>- Length4 ft.<br>- Thickness5/8 inch' WHERE item_no=20046 and size='S';
UPDATE Product_Size SET dimension='- Weight 40+ lbs<br>- Length 4 ft.<br>- Thickness1 inch' WHERE item_no=20047 and size='L';
UPDATE Product_Size SET dimension='- Weight 14–30 lbs<br>- Length4 ft.<br>- Thickness5/8 inch' WHERE item_no=20047 and size='S';
UPDATE Product_Size SET dimension='- Weight 40+ lbs<br>- Length 4 ft.<br>- Thickness1 inch' WHERE item_no=20048 and size='L';
UPDATE Product_Size SET dimension='- Weight 14–30 lbs<br>- Length4 ft.<br>- Thickness5/8 inch' WHERE item_no=20048 and size='S';
UPDATE Product_Size SET dimension='- Weight 40+ lbs<br>- Length 4 ft.<br>- Thickness1 inch' WHERE item_no=20049 and size='L';
UPDATE Product_Size SET dimension='- Weight 14–30 lbs<br>- Length4 ft.<br>- Thickness5/8 inch' WHERE item_no=20049 and size='S';
UPDATE Product_Size SET dimension='- Weight 40+ lbs<br>- Length 4 ft.<br>- Thickness1 inch' WHERE item_no=20050 and size='L';
UPDATE Product_Size SET dimension='- Weight 14–30 lbs<br>- Length4 ft.<br>- Thickness5/8 inch' WHERE item_no=20050 and size='S';
UPDATE Product_Size SET dimension='- Weight 40+ lbs<br>- Length 4 ft.<br>- Thickness1 inch' WHERE item_no=20051 and size='L';
UPDATE Product_Size SET dimension='- Weight 14–30 lbs<br>- Length4 ft.<br>- Thickness5/8 inch' WHERE item_no=20051 and size='S';
UPDATE Product_Size SET dimension='- Weight 40+ lbs<br>- Length 29.5 inches<br>- Thickness1 inch' WHERE item_no=20052 and size='L';
UPDATE Product_Size SET dimension='- Weight 40+ lbs<br>- Length 29.5 inches<br>- Thickness1 inch' WHERE item_no=20053 and size='L';
UPDATE Product_Size SET dimension='- Weight 40+ lbs<br>- Length 29.5 inches<br>- Thickness1 inch' WHERE item_no=20054 and size='L';
UPDATE Product_Size SET dimension='- Weight 40+ lbs<br>- Length 29.5 inches<br>- Thickness1 inch' WHERE item_no=20055 and size='L';
UPDATE Product_Size SET dimension='- Weight 40+ lbs<br>- Length 29.5 inches<br>- Thickness1 inch' WHERE item_no=20056 and size='L';
UPDATE Product_Size SET dimension='Girth 18 - 28 inches Thickness3/4 inch' WHERE item_no=20057 and size='M';
UPDATE Product_Size SET dimension='Girth 13 - 19 inches Thickness5/8 inch' WHERE item_no=20057 and size='S';
UPDATE Product_Size SET dimension='Girth 18 - 28 inches Thickness3/4 inch' WHERE item_no=20058 and size='M';
UPDATE Product_Size SET dimension='Girth 13 - 19 inches Thickness5/8 inch' WHERE item_no=20058 and size='S';
UPDATE Product_Size SET dimension='Girth 18 - 28 inches Thickness3/4 inch' WHERE item_no=20059 and size='M';
UPDATE Product_Size SET dimension='Girth 13 - 19 inches Thickness5/8 inch' WHERE item_no=20059 and size='S';
UPDATE Product_Size SET dimension='Girth 18 - 28 inches Thickness3/4 inch' WHERE item_no=20060 and size='M';
UPDATE Product_Size SET dimension='Girth 13 - 19 inches Thickness5/8 inch' WHERE item_no=20060 and size='S';
UPDATE Product_Size SET dimension='Girth 18 - 28 inches Thickness3/4 inch' WHERE item_no=20061 and size='M';
UPDATE Product_Size SET dimension='Girth 13 - 19 inches Thickness5/8 inch' WHERE item_no=20061 and size='S';
UPDATE Product_Size SET dimension='Girth 18 - 28 inches Thickness3/4 inch' WHERE item_no=20062 and size='M';
UPDATE Product_Size SET dimension='Girth 13 - 19 inches Thickness5/8 inch' WHERE item_no=20062 and size='S';
UPDATE Product_Size SET dimension='Girth 18 - 28 inches Thickness3/4 inch' WHERE item_no=20063 and size='M';
UPDATE Product_Size SET dimension='Girth 13 - 19 inches Thickness5/8 inch' WHERE item_no=20063 and size='S';

INSERT INTO `Product_Size`(`item_no`, `size`, `price`, `weight`, `dimension`) VALUES (30001,'-',0,0,'The sizes of the openings range from 1.2" x 0.75" (smallest) to 1.55" x 1.0" (largest)');
INSERT INTO `Product_Size`(`item_no`, `size`, `price`, `weight`, `dimension`) VALUES (30002,'-',0,0,'16.3" x 3.8" x 3.8"');
INSERT INTO `Product_Size`(`item_no`, `size`, `price`, `weight`, `dimension`) VALUES (30003,'-',0,0,'7.5" x 6.1" x 2.0"');
INSERT INTO `Product_Size`(`item_no`, `size`, `price`, `weight`, `dimension`) VALUES (30004,'-',0,0,'6.8" x 5.5" x 1.0"');
INSERT INTO `Product_Size`(`item_no`, `size`, `price`, `weight`, `dimension`) VALUES (30005,'-',0,0,'9.0" x 6.3" x 2.0"');
INSERT INTO `Product_Size`(`item_no`, `size`, `price`, `weight`, `dimension`) VALUES (30006,'-',0,0,'6.8" x 5.3" x 1.5"');
INSERT INTO `Product_Size`(`item_no`, `size`, `price`, `weight`, `dimension`) VALUES (30007,'-',0,0,'9.5" x 2.0" x 2.0"');
INSERT INTO `Product_Size`(`item_no`, `size`, `price`, `weight`, `dimension`) VALUES (30008,'-',0,0,'7.0" x 7.0" x 5.5"');
INSERT INTO `Product_Size`(`item_no`, `size`, `price`, `weight`, `dimension`) VALUES (30009,'-',0,0,'9.0" x 3.0" x 1.0"');
INSERT INTO `Product_Size`(`item_no`, `size`, `price`, `weight`, `dimension`) VALUES (30010,'-',0,0,'8.0" x 2.0" x 1.5"');
INSERT INTO `Product_Size`(`item_no`, `size`, `price`, `weight`, `dimension`) VALUES (30011,'-',0,0,'6.0" x 6.0" x 5.5"');
UPDATE Product_Size SET dimension='7 inches' WHERE item_no=30012 and size='S';
UPDATE Product_Size SET dimension='9 inches' WHERE item_no=30012 and size='L';
UPDATE Product_Size SET dimension='12 inches' WHERE item_no=30013 and size='XL';
UPDATE Product_Size SET dimension='9 inches' WHERE item_no=30013 and size='L';
INSERT INTO `Product_Size`(`item_no`, `size`, `price`, `weight`, `dimension`) VALUES (30014,'-',0,0,'7 inches');
INSERT INTO `Product_Size`(`item_no`, `size`, `price`, `weight`, `dimension`) VALUES (30015,'-',0,0,'7 inches');
INSERT INTO `Product_Size`(`item_no`, `size`, `price`, `weight`, `dimension`) VALUES (30016,'-',0,0,'7 inches');
UPDATE Product_Size SET dimension='7 inches' WHERE item_no=30017 and size='S';
UPDATE Product_Size SET dimension='10 inches' WHERE item_no=30017 and size='L';
UPDATE Product_Size SET dimension='7 inches' WHERE item_no=30018 and size='S';
UPDATE Product_Size SET dimension='10 inches' WHERE item_no=30018 and size='L';
INSERT INTO `Product_Size`(`item_no`, `size`, `price`, `weight`, `dimension`) VALUES (30019,'-',0,0,'9 inches');
UPDATE Product_Size SET dimension='3 inches' WHERE item_no=30020 and size='S';
UPDATE Product_Size SET dimension='5 inches' WHERE item_no=30020 and size='L';
UPDATE Product_Size SET dimension='7 inches' WHERE item_no=30021 and size='S';
UPDATE Product_Size SET dimension='9 inches' WHERE item_no=30021 and size='L';
UPDATE Product_Size SET dimension='12 inches' WHERE item_no=30021 and size='XL';
UPDATE Product_Size SET dimension='4 inches' WHERE item_no=30022 and size='S';
UPDATE Product_Size SET dimension='6 inches' WHERE item_no=30022 and size='L';
UPDATE Product_Size SET dimension='6 inches' WHERE item_no=30023 and size='S';
UPDATE Product_Size SET dimension='8 inches' WHERE item_no=30023 and size='L';
UPDATE Product_Size SET dimension='5 inches' WHERE item_no=30024 and size='S';
UPDATE Product_Size SET dimension='7 inches' WHERE item_no=30024 and size='L';
UPDATE Product_Size SET dimension='9 inches' WHERE item_no=30025 and size='S';
UPDATE Product_Size SET dimension='11 inches' WHERE item_no=30025 and size='L';
UPDATE Product_Size SET dimension='16 inches' WHERE item_no=30025 and size='XL';
UPDATE Product_Size SET dimension='4 inches' WHERE item_no=30026 and size='S';
UPDATE Product_Size SET dimension='6 inches' WHERE item_no=30026 and size='L';
UPDATE Product_Size SET dimension='7 inches' WHERE item_no=30027 and size='S';
UPDATE Product_Size SET dimension='9 inches' WHERE item_no=30027 and size='L';
UPDATE Product_Size SET dimension='5 inches' WHERE item_no=30028 and size='S';
UPDATE Product_Size SET dimension='7 inches' WHERE item_no=30028 and size='L';
INSERT INTO `Product_Size`(`item_no`, `size`, `price`, `weight`, `dimension`) VALUES (30029,'-',0,0,'9 inches');
UPDATE Product_Size SET dimension='5 inches' WHERE item_no=30030 and size='S';
UPDATE Product_Size SET dimension='7 inches' WHERE item_no=30030 and size='L';
UPDATE Product_Size SET dimension='10 inches' WHERE item_no=30031 and size='L';
UPDATE Product_Size SET dimension='13 inches' WHERE item_no=30031 and size='XL';
INSERT INTO `Product_Size`(`item_no`, `size`, `price`, `weight`, `dimension`) VALUES (30032,'-',0,0,'6 inches');
UPDATE Product_Size SET dimension='4 inches' WHERE item_no=30033 and size='S';
UPDATE Product_Size SET dimension='5 inches' WHERE item_no=30033 and size='L';
INSERT INTO `Product_Size`(`item_no`, `size`, `price`, `weight`, `dimension`) VALUES (30034,'-',0,0,'6 inches');
INSERT INTO `Product_Size`(`item_no`, `size`, `price`, `weight`, `dimension`) VALUES (30035,'-',0,0,'12 inches');
INSERT INTO `Product_Size`(`item_no`, `size`, `price`, `weight`, `dimension`) VALUES (30036,'-',0,0,'7 inches');
INSERT INTO `Product_Size`(`item_no`, `size`, `price`, `weight`, `dimension`) VALUES (30037,'-',0,0,'7 inches');
INSERT INTO `Product_Size`(`item_no`, `size`, `price`, `weight`, `dimension`) VALUES (30038,'-',0,0,'7 inches');
INSERT INTO `Product_Size`(`item_no`, `size`, `price`, `weight`, `dimension`) VALUES (30039,'-',0,0,'9 inches');
UPDATE Product_Size SET dimension='9 inches' WHERE item_no=30040 and size='L';
UPDATE Product_Size SET dimension='12 inches' WHERE item_no=30040 and size='XL';
INSERT INTO `Product_Size`(`item_no`, `size`, `price`, `weight`, `dimension`) VALUES (30041,'-',0,0,'10 inches');
INSERT INTO `Product_Size`(`item_no`, `size`, `price`, `weight`, `dimension`) VALUES (30042,'-',0,0,'7 inches');
UPDATE Product_Size SET dimension='4 inches' WHERE item_no=30043 and size='S';
UPDATE Product_Size SET dimension='9 inches' WHERE item_no=30043 and size='L';
UPDATE Product_Size SET dimension='9 inches' WHERE item_no=30044 and size='S';
UPDATE Product_Size SET dimension='12 inches' WHERE item_no=30044 and size='L';

UPDATE Product_Size SET dimension='Outer dimensions<br>- 24"L x 19"W x 7"H<br>Inner dimensions<br>- 16"L x 11"W<br>Weight Recommendation<br>- up to 25 lbs' WHERE item_no=50001 and size='S';
UPDATE Product_Size SET dimension='Outer dimensions<br>- 31"L X 25"W x 8"H<br>Inner dimensions<br>- 21"L x 16"W<br>Weight Recommendation<br>- up to 55 lbs' WHERE item_no=50001 and size='M';
UPDATE Product_Size SET dimension='Outer dimensions<br>- 24"L x 19"W x 7"H<br>Inner dimensions<br>- 16"L x 11"W<br>Weight Recommendation<br>- up to 25 lbs' WHERE item_no=50002 and size='S';
UPDATE Product_Size SET dimension='Outer dimensions<br>- 31"L X 25"W x 8"H<br>Inner dimensions<br>- 21"L x 16"W<br>Weight Recommendation<br>- up to 55 lbs' WHERE item_no=50002 and size='M';
UPDATE Product_Size SET dimension='Outer dimensions<br>- 24"L x 19"W x 7"H<br>Inner dimensions<br>- 16"L x 11"W<br>Weight Recommendation<br>- up to 25 lbs' WHERE item_no=50003 and size='S';
UPDATE Product_Size SET dimension='Outer dimensions<br>- 31"L X 25"W x 8"H<br>Inner dimensions<br>- 21"L x 16"W<br>Weight Recommendation<br>- up to 55 lbs' WHERE item_no=50003 and size='M';
UPDATE Product_Size SET dimension='Outer dimensions<br>- 24"L x 19"W x 7"H<br>Inner dimensions<br>- 16"L x 11"W<br>Weight Recommendation<br>- up to 25 lbs' WHERE item_no=50004 and size='S';
UPDATE Product_Size SET dimension='Outer dimensions<br>- 31"L X 25"W x 8"H<br>Inner dimensions<br>- 21"L x 16"W<br>Weight Recommendation<br>- up to 55 lbs' WHERE item_no=50004 and size='M';
UPDATE Product_Size SET dimension='Outer dimensions<br>- 24"L x 19"W x 7"H<br>Inner dimensions<br>- 16"L x 11"W<br>Weight Recommendation<br>- up to 25 lbs' WHERE item_no=50005 and size='S';
UPDATE Product_Size SET dimension='Outer dimensions<br>- 31"L X 25"W x 8"H<br>Inner dimensions<br>- 21"L x 16"W<br>Weight Recommendation<br>- up to 55 lbs' WHERE item_no=50005 and size='M';
UPDATE Product_Size SET dimension='36"x 27"x 5"' WHERE item_no=50006 and size='M';
UPDATE Product_Size SET dimension='36"' WHERE item_no=50007 and size='M';
UPDATE Product_Size SET dimension='36"' WHERE item_no=50008 and size='M';
UPDATE Product_Size SET dimension='36"' WHERE item_no=50009 and size='M';
UPDATE Product_Size SET dimension='Cup Diameter<br>- 13"<br>Flat Dimensions<br>- 16"x 18"<br>Weight Recommendation<br>- up to 12 lbs' WHERE item_no=50010 and size='S';
UPDATE Product_Size SET dimension='Cup Diameter<br>- 18"<br>Flat Dimensions<br>- 23"x 25"<br>Weight Recommendation<br>- up to 30 lbs' WHERE item_no=50010 and size='L';
UPDATE Product_Size SET dimension='Cup Diameter<br>- 13"<br>Flat Dimensions<br>- 16"x 18"<br>Weight Recommendation<br>- up to 12 lbs' WHERE item_no=50011 and size='S';
UPDATE Product_Size SET dimension='Cup Diameter<br>- 18"<br>Flat Dimensions<br>- 23"x 25"<br>Weight Recommendation<br>- up to 30 lbs' WHERE item_no=50011 and size='L';
UPDATE Product_Size SET dimension='Cup Diameter<br>- 13"<br>Flat Dimensions<br>- 16"x 18"<br>Weight Recommendation<br>- up to 12 lbs' WHERE item_no=50012 and size='S';
UPDATE Product_Size SET dimension='Cup Diameter<br>- 18"<br>Flat Dimensions<br>- 23"x 25"<br>Weight Recommendation<br>- up to 30 lbs' WHERE item_no=50012 and size='L';
