UPDATE `Product_Size` SET `dimension`= '<ul><li>12W x 12D x 6.5H inches</li><li>Weight - 10lbs</li><li>Holds up to 5.5 cups of dry food or 44 oz of water.</li></ul>' WHERE `item_no`='10001';
UPDATE `Product_Size` SET `dimension`= '<ul><li>10W x 10D x 5H inches</li><li>Weight - 4lbs</li><li>Holds up to 4.5 cups of dry food or 36 oz of water.</li></ul>' WHERE `item_no`='10001';
UPDATE `Product_Size` SET `dimension`= '<ul><li>8W x 8D x 3H inches</li><li>Weight - 2lbs</li><li>Holds up to 2 cups of dry food or 16 oz of water.</li></ul>' WHERE `item_no`='10001';
UPDATE `Product_Size` SET `dimension`= '<ul><li>9.25W x 9.25D x 4.25H inches</li><li>Weight - 5lbs</li><li>Holds up to 5.5 cups of dry food or 44 oz of water</li></ul>' WHERE `item_no`='10002';
UPDATE `Product_Size` SET `dimension`= '<ul><li>8W x 8D x 4H inches</li><li>Weight - 4lbs</li><li>Holds up to 4.5 cups of dry food or 36 oz of water.</li></ul>' WHERE `item_no`='10002';
UPDATE `Product_Size` SET `dimension`= '<ul><li>6.50W x 6.50D x 3H inches</li><li>Weight - 1lbs</li><li>Holds up to 2 cups of dry food or 16 oz of water</li></ul>' WHERE `item_no`='10002';
UPDATE `Product_Size` SET `dimension`= '<ul><li>14.50W x 8D x 5H inches</li><li>Weight - 2lbs</li><li>Holds up to 2 cups of dry food or 16 oz of water.</li></ul>' WHERE `item_no`='10003';
UPDATE `Product_Size` SET `dimension`= '<ul><li>7.50W x 7.50D x 4.50H inches</li><li>Weight - 2lbs</li><li>Holds up to 2 cups of dry food or 16 oz of water.</li></ul>' WHERE `item_no`='10004';
UPDATE `Product_Size` SET `dimension`= '<ul><li>7.50W x 7.50D x 4.50H inches</li><li>Weight - 2lbs</li><li>Holds up to 2 cups of dry food or 16 oz of water.</li></ul>' WHERE `item_no`='10005';
UPDATE `Product_Size` SET `dimension`= '<ul><li>8.75W x 8.75D x 3.75H inches</li><li>Weight - 2.5lbs</li><li>Holds up to 5.5 cups of dry food or 44 oz of water.</li></ul>' WHERE `item_no`='10006';
UPDATE `Product_Size` SET `dimension`= '<ul><li>8W x 8D x 3.25H inches</li><li>Weight - 2lbs</li><li>Holds up to 4.5 cups of dry food or 36 oz of water.</li></ul>' WHERE `item_no`='10006';
UPDATE `Product_Size` SET `dimension`= '<ul><li>6.5W x 6.5D x 3H inches</li><li>Weight - 1lbs</li><li>Holds up to 2 cups of dry food or 16 oz of water.</li></ul>' WHERE `item_no`='10006';
UPDATE `Product_Size` SET `dimension`= '<ul><li>10.5W x 10.5D x 4H inches</li><li>Weight - 4lbs</li><li>Holds up to 5.5 cups of dry food or 44 oz of water.</li></ul>' WHERE `item_no`='10007';
UPDATE `Product_Size` SET `dimension`= '<ul><li>10W x 10D x 3.5H inches</li><li>Weight - 3lbs</li><li>Holds up to 4.5 cups of dry food or 36 oz of water.</li></ul>' WHERE `item_no`='10007';
UPDATE `Product_Size` SET `dimension`= '<ul><li>8.5W x 8.5D x 2.75H inches</li><li>Weight - 2lbs</li><li>Holds up to 2 cups of dry food or 16 oz of water.</li></ul>' WHERE `item_no`='10007';
UPDATE `Product_Size` SET `dimension`= '<ul><li>7.25W x 7.25D x 4.5H inches</li><li>Weight - 4lbs</li><li>Holds up to 2 cups of dry food or 16 oz of water.</li></ul>' WHERE `item_no`='10008';
UPDATE `Product_Size` SET `dimension`= '<ul><li>10W x 10D x 12H inches</li><li>Weight - 12lbs</li><li>Holds up to 5.5 cups of dry food or 44 oz of water.</li></ul>' WHERE `item_no`='10009';
UPDATE `Product_Size` SET `dimension`= '<ul><li>9W x 9D x 9H inches</li><li>Weight - 8lbs</li><li>Holds up to 4.5 cups of dry food or 36 oz of water.</li></ul>' WHERE `item_no`='10009';
UPDATE `Product_Size` SET `dimension`= '<ul><li>8W x 8D x 4H inches</li><li>Weight - 3lbs</li><li>Holds up to 2 cups of dry food or 16 oz of water.</li></ul>' WHERE `item_no`='10009';
UPDATE `Product_Size` SET `dimension`= '<ul><li>10W x 10D x 12H inches</li><li>Weight - 12lbs</li><li>Holds up to 5.5 cups of dry food or 44 oz of water.</li></ul>' WHERE `item_no`='10010';
UPDATE `Product_Size` SET `dimension`= '<ul><li>9W x 9D x 9H inches</li><li>Weight - 8lbs</li><li>Holds up to 4.5 cups of dry food or 36 oz of water.</li></ul>' WHERE `item_no`='10010';
UPDATE `Product_Size` SET `dimension`= '<ul><li>8W x 8D x 4H inches</li><li>Weight - 3lbs</li><li>Holds up to 2 cups of dry food or 16 oz of water.</li></ul>' WHERE `item_no`='10010';
UPDATE `Product_Size` SET `dimension`= '<ul><li>15.75W x 8D x 4H inches</li><li>Weight - 3lbs</li><li>Holds up to 4.5 cups of dry food or 36 oz of water.</li></ul>' WHERE `item_no`='10011';
UPDATE `Product_Size` SET `dimension`= '<ul><li>12.5W x 8.5D x 4H inches</li><li>Weight - 2lbs</li><li>Holds up to 2 cups of dry food or 16 oz of water.</li></ul>' WHERE `item_no`='10011';
UPDATE `Product_Size` SET `dimension`= '<ul><li>7W x 2D x 3H inches</li><li>Weight - 4lbs</li><li>Holds up to 2.5 cups of dry food or 16 oz of water.</li></ul>' WHERE `item_no`='10012';
UPDATE `Product_Size` SET `dimension`= '<ul><li>5W x 1.5D x 2.5H inches</li><li>Weight - 2lbs</li><li>Holds up to 1.5 cups of dry food or 12 oz of water.</li></ul>' WHERE `item_no`='10012';
UPDATE `Product_Size` SET `dimension`= '<ul><li>7W x 2D x 3H inches</li><li>Weight - 4lbs</li><li>Holds up to 2.5 cups of dry food or 16 oz of water.</li></ul>' WHERE `item_no`='10013';
UPDATE `Product_Size` SET `dimension`= '<ul><li>5W x 1.5D x 2.5H inches</li><li>Weight - 2lbs</li><li>Holds up to 1.5 cups of dry food or 12 oz of water.</li></ul>' WHERE `item_no`='10013';
UPDATE `Product_Size` SET `dimension`= '<ul><li>Weight 40+ lbs</li><li>Length 19-22.5 inch</li><li>Thickness  1 inch</li></ul>' WHERE `item_no`='20001';
UPDATE `Product_Size` SET `dimension`= '<ul><li>Weight 30-40 lbs</li><li>Length 15-18 inch</li><li>Thickness  7/8 inch</li></ul>' WHERE `item_no`='20001';
UPDATE `Product_Size` SET `dimension`= '<ul><li>Weight 12-30 lbs</li><li>Length  12.5-15  inch</li><li>Thickness  5/8 inch</li></ul>' WHERE `item_no`='20001';
UPDATE `Product_Size` SET `dimension`= '<ul><li>Weight 5-12 lbs</li><li>Length 10-13 inch</li><li>Thickness  1/2  inch</li></ul>' WHERE `item_no`='20001';
UPDATE `Product_Size` SET `dimension`= '<ul><li>Weight 40+ lbs</li><li>Length 19-22.5 inch</li><li>Thickness  1 inch</li></ul>' WHERE `item_no`='20002';
UPDATE `Product_Size` SET `dimension`= '<ul><li>Weight 30-40 lbs</li><li>Length 15-18 inch</li><li>Thickness  7/8 inch</li></ul>' WHERE `item_no`='20002';
UPDATE `Product_Size` SET `dimension`= '<ul><li>Weight 12-30 lbs</li><li>Length  12.5-15  inch</li><li>Thickness  5/8 inch</li></ul>' WHERE `item_no`='20002';
UPDATE `Product_Size` SET `dimension`= '<ul><li>Weight 5-12 lbs</li><li>Length 10-13 inch</li><li>Thickness  1/2  inch</li></ul>' WHERE `item_no`='20002';
UPDATE `Product_Size` SET `dimension`= '<ul><li>Weight 40+ lbs</li><li>Length 19-22.5 inch</li><li>Thickness  1 inch</li></ul>' WHERE `item_no`='20003';
UPDATE `Product_Size` SET `dimension`= '<ul><li>Weight 30-40 lbs</li><li>Length 15-18 inch</li><li>Thickness  7/8 inch</li></ul>' WHERE `item_no`='20003';
UPDATE `Product_Size` SET `dimension`= '<ul><li>Weight 12-30 lbs</li><li>Length  12.5-15  inch</li><li>Thickness  5/8 inch</li></ul>' WHERE `item_no`='20003';
UPDATE `Product_Size` SET `dimension`= '<ul><li>Weight 5-12 lbs</li><li>Length 10-13 inch</li><li>Thickness  1/2  inch</li></ul>' WHERE `item_no`='20003';
UPDATE `Product_Size` SET `dimension`= '<ul><li>Weight 40+ lbs</li><li>Length 19-22.5 inch</li><li>Thickness  1 inch</li></ul>' WHERE `item_no`='20004';
UPDATE `Product_Size` SET `dimension`= '<ul><li>Weight 30-40 lbs</li><li>Length 15-18 inch</li><li>Thickness  7/8 inch</li></ul>' WHERE `item_no`='20004';
UPDATE `Product_Size` SET `dimension`= '<ul><li>Weight 12-30 lbs</li><li>Length  12.5-15  inch</li><li>Thickness  5/8 inch</li></ul>' WHERE `item_no`='20004';
UPDATE `Product_Size` SET `dimension`= '<ul><li>Weight 5-12 lbs</li><li>Length 10-13 inch</li><li>Thickness  1/2  inch</li></ul>' WHERE `item_no`='20004';
UPDATE `Product_Size` SET `dimension`= '<ul><li>Weight 40+ lbs</li><li>Length 19-22.5 inch</li><li>Thickness  1 inch</li></ul>' WHERE `item_no`='20005';
UPDATE `Product_Size` SET `dimension`= '<ul><li>Weight 30-40 lbs</li><li>Length 15-18 inch</li><li>Thickness  7/8 inch</li></ul>' WHERE `item_no`='20005';
UPDATE `Product_Size` SET `dimension`= '<ul><li>Weight 12-30 lbs</li><li>Length  12.5-15  inch</li><li>Thickness  5/8 inch</li></ul>' WHERE `item_no`='20005';
UPDATE `Product_Size` SET `dimension`= '<ul><li>Weight 5-12 lbs</li><li>Length 10-13 inch</li><li>Thickness  1/2  inch</li></ul>' WHERE `item_no`='20005';
UPDATE `Product_Size` SET `dimension`= '<ul><li>Weight 40+ lbs</li><li>Length 19-22.5 inch</li><li>Thickness  1 inch</li></ul>' WHERE `item_no`='20006';
UPDATE `Product_Size` SET `dimension`= '<ul><li>Weight 30-40 lbs</li><li>Length 15-18 inch</li><li>Thickness  7/8 inch</li></ul>' WHERE `item_no`='20006';
UPDATE `Product_Size` SET `dimension`= '<ul><li>Weight 12-30 lbs</li><li>Length  12.5-15  inch</li><li>Thickness  5/8 inch</li></ul>' WHERE `item_no`='20006';
UPDATE `Product_Size` SET `dimension`= '<ul><li>Weight 5-12 lbs</li><li>Length 10-13 inch</li><li>Thickness  1/2  inch</li></ul>' WHERE `item_no`='20006';
UPDATE `Product_Size` SET `dimension`= '<ul><li>Weight 40+ lbs</li><li>Length 19-27 inch</li><li>Thickness  1 inch</li></ul>' WHERE `item_no`='20007';
UPDATE `Product_Size` SET `dimension`= '<ul><li>Weight 30-40 lbs</li><li>Length 13.5-18.5 inch</li><li>Thickness  7/8 inch</li></ul>' WHERE `item_no`='20007';
UPDATE `Product_Size` SET `dimension`= '<ul><li>Weight 12-30 lbs</li><li>Length  10.5-13.5  inch</li><li>Thickness  5/8 inch</li></ul>' WHERE `item_no`='20007';
UPDATE `Product_Size` SET `dimension`= '<ul><li>Weight 5-12 lbs</li><li>Length 9-12  inch</li><li>Thickness  1/2  inch</li></ul>' WHERE `item_no`='20007';
UPDATE `Product_Size` SET `dimension`= '<ul><li>Weight 40+ lbs</li><li>Length 19-22.5 inch</li><li>Thickness  1 inch</li></ul>' WHERE `item_no`='20008';
UPDATE `Product_Size` SET `dimension`= '<ul><li>Weight 30-40 lbs</li><li>Length 15-18 inch</li><li>Thickness  7/8 inch</li></ul>' WHERE `item_no`='20008';
UPDATE `Product_Size` SET `dimension`= '<ul><li>Weight 12-30 lbs</li><li>Length  12.5-15  inch</li><li>Thickness  5/8 inch</li></ul>' WHERE `item_no`='20008';
UPDATE `Product_Size` SET `dimension`= '<ul><li>Weight 5-12 lbs</li><li>Length 10-13 inch</li><li>Thickness  1/2  inch</li></ul>' WHERE `item_no`='20008';
UPDATE `Product_Size` SET `dimension`= '<ul><li>Weight 40+ lbs</li><li>Length 19-22.5 inch</li><li>Thickness  1 inch</li></ul>' WHERE `item_no`='20009';
UPDATE `Product_Size` SET `dimension`= '<ul><li>Weight 30-40 lbs</li><li>Length 15-18 inch</li><li>Thickness  7/8 inch</li></ul>' WHERE `item_no`='20009';
UPDATE `Product_Size` SET `dimension`= '<ul><li>Weight 12-30 lbs</li><li>Length  12.5-15  inch</li><li>Thickness  5/8 inch</li></ul>' WHERE `item_no`='20009';
UPDATE `Product_Size` SET `dimension`= '<ul><li>Weight 5-12 lbs</li><li>Length 10-13 inch</li><li>Thickness  1/2  inch</li></ul>' WHERE `item_no`='20009';
UPDATE `Product_Size` SET `dimension`= '<ul><li>Weight 40+ lbs</li><li>Length 19-22.5 inch</li><li>Thickness  1 inch</li></ul>' WHERE `item_no`='20010';
UPDATE `Product_Size` SET `dimension`= '<ul><li>Weight 30-40 lbs</li><li>Length 15-18 inch</li><li>Thickness  7/8 inch</li></ul>' WHERE `item_no`='20010';
UPDATE `Product_Size` SET `dimension`= '<ul><li>Weight 12-30 lbs</li><li>Length  12.5-15  inch</li><li>Thickness  5/8 inch</li></ul>' WHERE `item_no`='20010';
UPDATE `Product_Size` SET `dimension`= '<ul><li>Weight 5-12 lbs</li><li>Length 10-13 inch</li><li>Thickness  1/2  inch</li></ul>' WHERE `item_no`='20010';
UPDATE `Product_Size` SET `dimension`= '<ul><li>Weight 35+ lbs</li><li>Length 7 ft.</li><li>Thickness  12 mm</li></ul>' WHERE `item_no`='20011';
UPDATE `Product_Size` SET `dimension`= '<ul><li>Weight 12 - 30 lbs</li><li>Length 7 ft.</li><li>Thickness  8 mm</li></ul>' WHERE `item_no`='20011';
UPDATE `Product_Size` SET `dimension`= '<ul><li>Weight 5 - 12 lbs</li><li>Length  7 ft.</li><li>Thickness  6 mm</li></ul>' WHERE `item_no`='20011';
UPDATE `Product_Size` SET `dimension`= '<ul><li>Weight 35+ lbs</li><li>Length 7 ft.</li><li>Thickness  12 mm</li></ul>' WHERE `item_no`='20012';
UPDATE `Product_Size` SET `dimension`= '<ul><li>Weight 12 - 30 lbs</li><li>Length 7 ft.</li><li>Thickness  8 mm</li></ul>' WHERE `item_no`='20012';
UPDATE `Product_Size` SET `dimension`= '<ul><li>Weight 5 - 12 lbs</li><li>Length  7 ft.</li><li>Thickness  6 mm</li></ul>' WHERE `item_no`='20012';
UPDATE `Product_Size` SET `dimension`= '<ul><li>Weight 35+ lbs</li><li>Length 7 ft.</li><li>Thickness  12 mm</li></ul>' WHERE `item_no`='20013';
UPDATE `Product_Size` SET `dimension`= '<ul><li>Weight 12 - 30 lbs</li><li>Length 7 ft.</li><li>Thickness  8 mm</li></ul>' WHERE `item_no`='20013';
UPDATE `Product_Size` SET `dimension`= '<ul><li>Weight 5 - 12 lbs</li><li>Length  7 ft.</li><li>Thickness  6 mm</li></ul>' WHERE `item_no`='20013';
UPDATE `Product_Size` SET `dimension`= '<ul><li>Weight 35+ lbs</li><li>Length 7 ft.</li><li>Thickness  12 mm</li></ul>' WHERE `item_no`='20014';
UPDATE `Product_Size` SET `dimension`= '<ul><li>Weight 12 - 30 lbs</li><li>Length 7 ft.</li><li>Thickness  8 mm</li></ul>' WHERE `item_no`='20014';
UPDATE `Product_Size` SET `dimension`= '<ul><li>Weight 5 - 12 lbs</li><li>Length  7 ft.</li><li>Thickness  6 mm</li></ul>' WHERE `item_no`='20014';
UPDATE `Product_Size` SET `dimension`= '<ul><li>Weight 35+ lbs</li><li>Length 7 ft.</li><li>Thickness  12 mm</li></ul>' WHERE `item_no`='20015';
UPDATE `Product_Size` SET `dimension`= '<ul><li>Weight 12 - 30 lbs</li><li>Length 7 ft.</li><li>Thickness  8 mm</li></ul>' WHERE `item_no`='20015';
UPDATE `Product_Size` SET `dimension`= '<ul><li>Weight 5 - 12 lbs</li><li>Length  7 ft.</li><li>Thickness  6 mm</li></ul>' WHERE `item_no`='20015';
UPDATE `Product_Size` SET `dimension`= '<ul><li>Weight 35+ lbs</li><li>Length 7 ft.</li><li>Thickness  12 mm</li></ul>' WHERE `item_no`='20016';
UPDATE `Product_Size` SET `dimension`= '<ul><li>Weight 12 - 30 lbs</li><li>Length 7 ft.</li><li>Thickness  8 mm</li></ul>' WHERE `item_no`='20016';
UPDATE `Product_Size` SET `dimension`= '<ul><li>Weight 5 - 12 lbs</li><li>Length  7 ft.</li><li>Thickness  6 mm</li></ul>' WHERE `item_no`='20016';
UPDATE `Product_Size` SET `dimension`= '<ul><li>Weight 35+ lbs</li><li>Length 7 ft.</li><li>Thickness  12 mm</li></ul>' WHERE `item_no`='20017';
UPDATE `Product_Size` SET `dimension`= '<ul><li>Weight 12 - 30 lbs</li><li>Length 7 ft.</li><li>Thickness  8 mm</li></ul>' WHERE `item_no`='20017';
UPDATE `Product_Size` SET `dimension`= '<ul><li>Weight 5 - 12 lbs</li><li>Length  7 ft.</li><li>Thickness  6 mm</li></ul>' WHERE `item_no`='20017';
UPDATE `Product_Size` SET `dimension`= '<ul><li>Weight 35+ lbs</li><li>Length 7 ft.</li><li>Thickness  12 mm</li></ul>' WHERE `item_no`='20018';
UPDATE `Product_Size` SET `dimension`= '<ul><li>Weight 12 - 30 lbs</li><li>Length 7 ft.</li><li>Thickness  8 mm</li></ul>' WHERE `item_no`='20018';
UPDATE `Product_Size` SET `dimension`= '<ul><li>Weight 5 - 12 lbs</li><li>Length  7 ft.</li><li>Thickness  6 mm</li></ul>' WHERE `item_no`='20018';
UPDATE `Product_Size` SET `dimension`= '<ul><li>Weight 35+ lbs</li><li>Length 7 ft.</li><li>Thickness12 mm</li></ul>' WHERE `item_no`='20019';
UPDATE `Product_Size` SET `dimension`= '<ul><li>Weight 12 - 30 lbs</li><li>Length 7 ft.</li><li>Thickness8 mm</li></ul>' WHERE `item_no`='20019';
UPDATE `Product_Size` SET `dimension`= '<ul><li>Weight 5 - 12 lbs</li><li>Length7 ft.</li><li>Thickness6 mm</li></ul>' WHERE `item_no`='20019';
UPDATE `Product_Size` SET `dimension`= '<ul><li>Weight 35+ lbs</li><li>Length 7 ft.</li><li>Thickness12 mm</li></ul>' WHERE `item_no`='20020';
UPDATE `Product_Size` SET `dimension`= '<ul><li>Weight 12 - 30 lbs</li><li>Length 7 ft.</li><li>Thickness8 mm</li></ul>' WHERE `item_no`='20020';
UPDATE `Product_Size` SET `dimension`= '<ul><li>Weight 5 - 12 lbs</li><li>Length7 ft.</li><li>Thickness6 mm</li></ul>' WHERE `item_no`='20020';
UPDATE `Product_Size` SET `dimension`= '<ul><li>Weight 35+ lbs</li><li>Length 5 ft.</li><li>Thickness12 mm</li></ul>' WHERE `item_no`='20021';
UPDATE `Product_Size` SET `dimension`= '<ul><li>Weight 12 - 30 lbs</li><li>Length 5 ft.</li><li>Thickness8 mm</li></ul>' WHERE `item_no`='20021';
UPDATE `Product_Size` SET `dimension`= '<ul><li>Weight 5 - 12 lbs</li><li>Length5 ft.</li><li>Thickness6 mm</li></ul>' WHERE `item_no`='20021';
UPDATE `Product_Size` SET `dimension`= '<ul><li>Weight 35+ lbs</li><li>Length 5 ft.</li><li>Thickness12 mm</li></ul>' WHERE `item_no`='20022';
UPDATE `Product_Size` SET `dimension`= '<ul><li>Weight 12 - 30 lbs</li><li>Length 5 ft.</li><li>Thickness8 mm</li></ul>' WHERE `item_no`='20022';
UPDATE `Product_Size` SET `dimension`= '<ul><li>Weight 5 - 12 lbs</li><li>Length5 ft.</li><li>Thickness6 mm</li></ul>' WHERE `item_no`='20022';
UPDATE `Product_Size` SET `dimension`= '<ul><li>Weight 35+ lbs</li><li>Length 5 ft.</li><li>Thickness12 mm</li></ul>' WHERE `item_no`='20023';
UPDATE `Product_Size` SET `dimension`= '<ul><li>Weight 12 - 30 lbs</li><li>Length 5 ft.</li><li>Thickness8 mm</li></ul>' WHERE `item_no`='20023';
UPDATE `Product_Size` SET `dimension`= '<ul><li>Weight 5 - 12 lbs</li><li>Length5 ft.</li><li>Thickness6 mm</li></ul>' WHERE `item_no`='20023';
UPDATE `Product_Size` SET `dimension`= '<ul><li>Weight 40+ lbs</li><li>Length18 - 26 inches</li><li>Thickness1 inch</li></ul>' WHERE `item_no`='20024';
UPDATE `Product_Size` SET `dimension`= '<ul><li>Weight 30-40 lbs</li><li>Length14 - 20 inches</li><li>Thickness5/4 inch</li></ul>' WHERE `item_no`='20024';
UPDATE `Product_Size` SET `dimension`= '<ul><li>Weight 14-30 lbs</li><li>Length11 - 16 inches</li><li>Thickness5/8 inch</li></ul>' WHERE `item_no`='20024';
UPDATE `Product_Size` SET `dimension`= '<ul><li>Weight 40+ lbs</li><li>Length18 - 26 inches</li><li>Thickness1 inch</li></ul>' WHERE `item_no`='20025';
UPDATE `Product_Size` SET `dimension`= '<ul><li>Weight 30-40 lbs</li><li>Length14 - 20 inches</li><li>Thickness5/4 inch</li></ul>' WHERE `item_no`='20025';
UPDATE `Product_Size` SET `dimension`= '<ul><li>Weight 14-30 lbs</li><li>Length11 - 16 inches</li><li>Thickness5/8 inch</li></ul>' WHERE `item_no`='20025';
UPDATE `Product_Size` SET `dimension`= '<ul><li>Weight 40+ lbs</li><li>Length18 - 26 inches</li><li>Thickness1 inch</li></ul>' WHERE `item_no`='20026';
UPDATE `Product_Size` SET `dimension`= '<ul><li>Weight 30-40 lbs</li><li>Length14 - 20 inches</li><li>Thickness5/4 inch</li></ul>' WHERE `item_no`='20026';
UPDATE `Product_Size` SET `dimension`= '<ul><li>Weight 14-30 lbs</li><li>Length11 - 16 inches</li><li>Thickness5/8 inch</li></ul>' WHERE `item_no`='20026';
UPDATE `Product_Size` SET `dimension`= '<ul><li>Weight 40+ lbs</li><li>Length18 - 26 inches</li><li>Thickness1 inch</li></ul>' WHERE `item_no`='20027';
UPDATE `Product_Size` SET `dimension`= '<ul><li>Weight 30-40 lbs</li><li>Length14 - 20 inches</li><li>Thickness5/4 inch</li></ul>' WHERE `item_no`='20027';
UPDATE `Product_Size` SET `dimension`= '<ul><li>Weight 14-30 lbs</li><li>Length11 - 16 inches</li><li>Thickness5/8 inch</li></ul>' WHERE `item_no`='20027';
UPDATE `Product_Size` SET `dimension`= '<ul><li>Weight 40+ lbs</li><li>Length18 - 26 inches</li><li>Thickness1 inch</li></ul>' WHERE `item_no`='20028';
UPDATE `Product_Size` SET `dimension`= '<ul><li>Weight 30-40 lbs</li><li>Length14 - 20 inches</li><li>Thickness5/4 inch</li></ul>' WHERE `item_no`='20028';
UPDATE `Product_Size` SET `dimension`= '<ul><li>Weight 14-30 lbs</li><li>Length11 - 16 inches</li><li>Thickness5/8 inch</li></ul>' WHERE `item_no`='20028';
UPDATE `Product_Size` SET `dimension`= '<ul><li>Weight 40+ lbs</li><li>Length18 - 26 inches</li><li>Thickness1 inch</li></ul>' WHERE `item_no`='20029';
UPDATE `Product_Size` SET `dimension`= '<ul><li>Weight 30-40 lbs</li><li>Length14 - 20 inches</li><li>Thickness5/4 inch</li></ul>' WHERE `item_no`='20029';
UPDATE `Product_Size` SET `dimension`= '<ul><li>Weight 14-30 lbs</li><li>Length11 - 16 inches</li><li>Thickness5/8 inch</li></ul>' WHERE `item_no`='20029';
UPDATE `Product_Size` SET `dimension`= '<ul><li>Weight 40+ lbs</li><li>Length18 - 26 inches</li><li>Thickness1 inch</li></ul>' WHERE `item_no`='20030';
UPDATE `Product_Size` SET `dimension`= '<ul><li>Weight 30-40 lbs</li><li>Length14 - 20 inches</li><li>Thickness5/4 inch</li></ul>' WHERE `item_no`='20030';
UPDATE `Product_Size` SET `dimension`= '<ul><li>Weight 14-30 lbs</li><li>Length11 - 16 inches</li><li>Thickness5/8 inch</li></ul>' WHERE `item_no`='20030';
UPDATE `Product_Size` SET `dimension`= '<ul><li>Weight 40+ lbs</li><li>Length18 - 26 inches</li><li>Thickness1 inch</li></ul>' WHERE `item_no`='20031';
UPDATE `Product_Size` SET `dimension`= '<ul><li>Weight 30-40 lbs</li><li>Length14 - 20 inches</li><li>Thickness5/4 inch</li></ul>' WHERE `item_no`='20031';
UPDATE `Product_Size` SET `dimension`= '<ul><li>Weight 14-30 lbs</li><li>Length11 - 16 inches</li><li>Thickness5/8 inch</li></ul>' WHERE `item_no`='20031';
UPDATE `Product_Size` SET `dimension`= '<ul><li>Weight 40+ lbs</li><li>Length18 - 26 inches</li><li>Thickness1 inch</li></ul>' WHERE `item_no`='20032';
UPDATE `Product_Size` SET `dimension`= '<ul><li>Weight 30-40 lbs</li><li>Length14 - 20 inches</li><li>Thickness5/4 inch</li></ul>' WHERE `item_no`='20032';
UPDATE `Product_Size` SET `dimension`= '<ul><li>Weight 14-30 lbs</li><li>Length11 - 16 inches</li><li>Thickness5/8 inch</li></ul>' WHERE `item_no`='20032';
UPDATE `Product_Size` SET `dimension`= '<ul><li>Weight 40+ lbs</li><li>Length18 - 26 inches</li><li>Thickness1 inch</li></ul>' WHERE `item_no`='20033';
UPDATE `Product_Size` SET `dimension`= '<ul><li>Weight 30-40 lbs</li><li>Length14 - 20 inches</li><li>Thickness5/4 inch</li></ul>' WHERE `item_no`='20033';
UPDATE `Product_Size` SET `dimension`= '<ul><li>Weight 14-30 lbs</li><li>Length11 - 16 inches</li><li>Thickness5/8 inch</li></ul>' WHERE `item_no`='20033';
UPDATE `Product_Size` SET `dimension`= '<ul><li>Weight 40+ lbs</li><li>Length18 - 26 inches</li><li>Thickness1 inch</li></ul>' WHERE `item_no`='20034';
UPDATE `Product_Size` SET `dimension`= '<ul><li>Weight 30-40 lbs</li><li>Length14 - 20 inches</li><li>Thickness5/4 inch</li></ul>' WHERE `item_no`='20034';
UPDATE `Product_Size` SET `dimension`= '<ul><li>Weight 14-30 lbs</li><li>Length11 - 16 inches</li><li>Thickness5/8 inch</li></ul>' WHERE `item_no`='20034';
UPDATE `Product_Size` SET `dimension`= '<ul><li>Weight 40+ lbs</li><li>Length18 - 26 inches</li><li>Thickness1 inch</li></ul>' WHERE `item_no`='20035';
UPDATE `Product_Size` SET `dimension`= '<ul><li>Weight 30-40 lbs</li><li>Length14 - 20 inches</li><li>Thickness5/4 inch</li></ul>' WHERE `item_no`='20035';
UPDATE `Product_Size` SET `dimension`= '<ul><li>Weight 14-30 lbs</li><li>Length11 - 16 inches</li><li>Thickness5/8 inch</li></ul>' WHERE `item_no`='20035';
UPDATE `Product_Size` SET `dimension`= '<ul><li>Weight 40+ lbs</li><li>Length18 - 26 inches</li><li>Thickness1 inch</li></ul>' WHERE `item_no`='20036';
UPDATE `Product_Size` SET `dimension`= '<ul><li>Weight 30-40 lbs</li><li>Length14 - 20 inches</li><li>Thickness5/4 inch</li></ul>' WHERE `item_no`='20036';
UPDATE `Product_Size` SET `dimension`= '<ul><li>Weight 14-30 lbs</li><li>Length11 - 16 inches</li><li>Thickness5/8 inch</li></ul>' WHERE `item_no`='20036';
UPDATE `Product_Size` SET `dimension`= '<ul><li>Weight 40+ lbs</li><li>Length18 - 26 inches</li><li>Thickness1 inch</li></ul>' WHERE `item_no`='20037';
UPDATE `Product_Size` SET `dimension`= '<ul><li>Weight 30-40 lbs</li><li>Length14 - 20 inches</li><li>Thickness5/4 inch</li></ul>' WHERE `item_no`='20037';
UPDATE `Product_Size` SET `dimension`= '<ul><li>Weight 14-30 lbs</li><li>Length11 - 16 inches</li><li>Thickness5/8 inch</li></ul>' WHERE `item_no`='20037';
UPDATE `Product_Size` SET `dimension`= '<ul><li>Weight 40+ lbs</li><li>Length 4 ft.</li><li>Thickness1 inch</li></ul>' WHERE `item_no`='20038';
UPDATE `Product_Size` SET `dimension`= '<ul><li>Weight 14-30 lbs</li><li>Length4 ft.</li><li>Thickness5/8 inch</li></ul>' WHERE `item_no`='20038';
UPDATE `Product_Size` SET `dimension`= '<ul><li>Weight 40+ lbs</li><li>Length 4 ft.</li><li>Thickness1 inch</li></ul>' WHERE `item_no`='20039';
UPDATE `Product_Size` SET `dimension`= '<ul><li>Weight 14-30 lbs</li><li>Length4 ft.</li><li>Thickness5/8 inch</li></ul>' WHERE `item_no`='20039';
UPDATE `Product_Size` SET `dimension`= '<ul><li>Weight 40+ lbs</li><li>Length 4 ft.</li><li>Thickness1 inch</li></ul>' WHERE `item_no`='20040';
UPDATE `Product_Size` SET `dimension`= '<ul><li>Weight 14-30 lbs</li><li>Length4 ft.</li><li>Thickness5/8 inch</li></ul>' WHERE `item_no`='20040';
UPDATE `Product_Size` SET `dimension`= '<ul><li>Weight 40+ lbs</li><li>Length 4 ft.</li><li>Thickness1 inch</li></ul>' WHERE `item_no`='20041';
UPDATE `Product_Size` SET `dimension`= '<ul><li>Weight 14-30 lbs</li><li>Length4 ft.</li><li>Thickness5/8 inch</li></ul>' WHERE `item_no`='20041';
UPDATE `Product_Size` SET `dimension`= '<ul><li>Weight 40+ lbs</li><li>Length 4 ft.</li><li>Thickness1 inch</li></ul>' WHERE `item_no`='20042';
UPDATE `Product_Size` SET `dimension`= '<ul><li>Weight 14-30 lbs</li><li>Length4 ft.</li><li>Thickness5/8 inch</li></ul>' WHERE `item_no`='20042';
UPDATE `Product_Size` SET `dimension`= '<ul><li>Weight 40+ lbs</li><li>Length 4 ft.</li><li>Thickness1 inch</li></ul>' WHERE `item_no`='20043';
UPDATE `Product_Size` SET `dimension`= '<ul><li>Weight 14-30 lbs</li><li>Length4 ft.</li><li>Thickness5/8 inch</li></ul>' WHERE `item_no`='20043';
UPDATE `Product_Size` SET `dimension`= '<ul><li>Weight 40+ lbs</li><li>Length 4 ft.</li><li>Thickness1 inch</li></ul>' WHERE `item_no`='20044';
UPDATE `Product_Size` SET `dimension`= '<ul><li>Weight 14-30 lbs</li><li>Length4 ft.</li><li>Thickness5/8 inch</li></ul>' WHERE `item_no`='20044';
UPDATE `Product_Size` SET `dimension`= '<ul><li>Weight 40+ lbs</li><li>Length 4 ft.</li><li>Thickness1 inch</li></ul>' WHERE `item_no`='20045';
UPDATE `Product_Size` SET `dimension`= '<ul><li>Weight 14-30 lbs</li><li>Length4 ft.</li><li>Thickness5/8 inch</li></ul>' WHERE `item_no`='20045';
UPDATE `Product_Size` SET `dimension`= '<ul><li>Weight 40+ lbs</li><li>Length 4 ft.</li><li>Thickness1 inch</li></ul>' WHERE `item_no`='20046';
UPDATE `Product_Size` SET `dimension`= '<ul><li>Weight 14-30 lbs</li><li>Length4 ft.</li><li>Thickness5/8 inch</li></ul>' WHERE `item_no`='20046';
UPDATE `Product_Size` SET `dimension`= '<ul><li>Weight 40+ lbs</li><li>Length 4 ft.</li><li>Thickness1 inch</li></ul>' WHERE `item_no`='20047';
UPDATE `Product_Size` SET `dimension`= '<ul><li>Weight 14-30 lbs</li><li>Length4 ft.</li><li>Thickness5/8 inch</li></ul>' WHERE `item_no`='20047';
UPDATE `Product_Size` SET `dimension`= '<ul><li>Weight 40+ lbs</li><li>Length 4 ft.</li><li>Thickness1 inch</li></ul>' WHERE `item_no`='20048';
UPDATE `Product_Size` SET `dimension`= '<ul><li>Weight 14-30 lbs</li><li>Length4 ft.</li><li>Thickness5/8 inch</li></ul>' WHERE `item_no`='20048';
UPDATE `Product_Size` SET `dimension`= '<ul><li>Weight 40+ lbs</li><li>Length 4 ft.</li><li>Thickness1 inch</li></ul>' WHERE `item_no`='20049';
UPDATE `Product_Size` SET `dimension`= '<ul><li>Weight 14-30 lbs</li><li>Length4 ft.</li><li>Thickness5/8 inch</li></ul>' WHERE `item_no`='20049';
UPDATE `Product_Size` SET `dimension`= '<ul><li>Weight 40+ lbs</li><li>Length 4 ft.</li><li>Thickness1 inch</li></ul>' WHERE `item_no`='20050';
UPDATE `Product_Size` SET `dimension`= '<ul><li>Weight 14-30 lbs</li><li>Length4 ft.</li><li>Thickness5/8 inch</li></ul>' WHERE `item_no`='20050';
UPDATE `Product_Size` SET `dimension`= '<ul><li>Weight 40+ lbs</li><li>Length 4 ft.</li><li>Thickness1 inch</li></ul>' WHERE `item_no`='20051';
UPDATE `Product_Size` SET `dimension`= '<ul><li>Weight 14-30 lbs</li><li>Length4 ft.</li><li>Thickness5/8 inch</li></ul>' WHERE `item_no`='20051';
UPDATE `Product_Size` SET `dimension`= '<ul><li>Weight 40+ lbs</li><li>Length 29.5 inches</li><li>Thickness1 inch</li></ul>' WHERE `item_no`='20052';
UPDATE `Product_Size` SET `dimension`= '<ul><li>Weight 40+ lbs</li><li>Length 29.5 inches</li><li>Thickness1 inch</li></ul>' WHERE `item_no`='20053';
UPDATE `Product_Size` SET `dimension`= '<ul><li>Weight 40+ lbs</li><li>Length 29.5 inches</li><li>Thickness1 inch</li></ul>' WHERE `item_no`='20054';
UPDATE `Product_Size` SET `dimension`= '<ul><li>Weight 40+ lbs</li><li>Length 29.5 inches</li><li>Thickness1 inch</li></ul>' WHERE `item_no`='20055';
UPDATE `Product_Size` SET `dimension`= '<ul><li>Weight 40+ lbs</li><li>Length 29.5 inches</li><li>Thickness1 inch</li></ul>' WHERE `item_no`='20056';
UPDATE `Product_Size` SET `dimension`= '<ul><li>Girth 18 - 28 inches</li><li>Thickness3/4 inch</li></ul>' WHERE `item_no`='20057';
UPDATE `Product_Size` SET `dimension`= '<ul><li>Girth 13 - 19 inches</li><li>Thickness5/8 inch</li></ul>' WHERE `item_no`='20057';
UPDATE `Product_Size` SET `dimension`= '<ul><li>Girth 18 - 28 inches</li><li>Thickness3/4 inch</li></ul>' WHERE `item_no`='20058';
UPDATE `Product_Size` SET `dimension`= '<ul><li>Girth 13 - 19 inches</li><li>Thickness5/8 inch</li></ul>' WHERE `item_no`='20058';
UPDATE `Product_Size` SET `dimension`= '<ul><li>Girth 18 - 28 inches</li><li>Thickness3/4 inch</li></ul>' WHERE `item_no`='20059';
UPDATE `Product_Size` SET `dimension`= '<ul><li>Girth 13 - 19 inches</li><li>Thickness5/8 inch</li></ul>' WHERE `item_no`='20059';
UPDATE `Product_Size` SET `dimension`= '<ul><li>Girth 18 - 28 inches</li><li>Thickness3/4 inch</li></ul>' WHERE `item_no`='20060';
UPDATE `Product_Size` SET `dimension`= '<ul><li>Girth 13 - 19 inches</li><li>Thickness5/8 inch</li></ul>' WHERE `item_no`='20060';
UPDATE `Product_Size` SET `dimension`= '<ul><li>Girth 18 - 28 inches</li><li>Thickness3/4 inch</li></ul>' WHERE `item_no`='20061';
UPDATE `Product_Size` SET `dimension`= '<ul><li>Girth 13 - 19 inches</li><li>Thickness5/8 inch</li></ul>' WHERE `item_no`='20061';
UPDATE `Product_Size` SET `dimension`= '<ul><li>Girth 18 - 28 inches</li><li>Thickness3/4 inch</li></ul>' WHERE `item_no`='20062';
UPDATE `Product_Size` SET `dimension`= '<ul><li>Girth 13 - 19 inches</li><li>Thickness5/8 inch</li></ul>' WHERE `item_no`='20062';
UPDATE `Product_Size` SET `dimension`= '<ul><li>Girth 18 - 28 inches</li><li>Thickness3/4 inch</li></ul>' WHERE `item_no`='20063';
UPDATE `Product_Size` SET `dimension`= '<ul><li>Girth 13 - 19 inches</li><li>Thickness5/8 inch</li></ul>' WHERE `item_no`='20063';
UPDATE `Product_Size` SET `dimension`= 'Outer dimensions<ul><li>24"L x 19"W x 7"H</li></ul>Inner dimensions<ul><li>16"L x 11"W</li></ul>Weight Recommendation<ul><li>up to 25 lbs</li></ul>' WHERE `item_no`='50002';
UPDATE `Product_Size` SET `dimension`= 'Outer dimensions<ul><li>31"L X 25"W x 8"H</li></ul>Inner dimensions<ul><li>21"L x 16"W</li></ul>Weight Recommendation<ul><li>up to 55 lbs</li></ul>' WHERE `item_no`='50002';
UPDATE `Product_Size` SET `dimension`= 'Outer dimensions<ul><li>24"L x 19"W x 7"H</li></ul>Inner dimensions<ul><li>16"L x 11"W</li></ul>Weight Recommendation<ul><li>up to 25 lbs</li></ul>' WHERE `item_no`='50003';
UPDATE `Product_Size` SET `dimension`= 'Outer dimensions<ul><li>31"L X 25"W x 8"H</li></ul>Inner dimensions<ul><li>21"L x 16"W</li></ul>Weight Recommendation<ul><li>up to 55 lbs</li></ul>' WHERE `item_no`='50003';
UPDATE `Product_Size` SET `dimension`= 'Outer dimensions<ul><li>24"L x 19"W x 7"H</li></ul>Inner dimensions<ul><li>16"L x 11"W</li></ul>Weight Recommendation<ul><li>up to 25 lbs</li></ul>' WHERE `item_no`='50004';
UPDATE `Product_Size` SET `dimension`= 'Outer dimensions<ul><li>31"L X 25"W x 8"H</li></ul>Inner dimensions<ul><li>21"L x 16"W</li></ul>Weight Recommendation<ul><li>up to 55 lbs</li></ul>' WHERE `item_no`='50004';
UPDATE `Product_Size` SET `dimension`= 'Outer dimensions<ul><li>24"L x 19"W x 7"H</li></ul>Inner dimensions<ul><li>16"L x 11"W</li></ul>Weight Recommendation<ul><li>up to 25 lbs</li></ul>' WHERE `item_no`='50005';
UPDATE `Product_Size` SET `dimension`= 'Outer dimensions<ul><li>31"L X 25"W x 8"H</li></ul>Inner dimensions<ul><li>21"L x 16"W</li></ul>Weight Recommendation<ul><li>up to 55 lbs</li></ul>' WHERE `item_no`='50005';
UPDATE `Product_Size` SET `dimension`= 'Cup Diameter<ul><li>13"</li></ul>Flat Dimensions<ul><li>16"x 18"</li></ul>Weight Recommendation<ul><li>up to 12 lbs</li></ul>' WHERE `item_no`='50010';
UPDATE `Product_Size` SET `dimension`= 'Cup Diameter<ul><li>18"</li></ul>Flat Dimensions<ul><li>23"x 25"</li></ul>Weight Recommendation<ul><li>up to 30 lbs</li></ul>' WHERE `item_no`='50010';
UPDATE `Product_Size` SET `dimension`= 'Cup Diameter<ul><li>13"</li></ul>Flat Dimensions<ul><li>16"x 18"</li></ul>Weight Recommendation<ul><li>up to 12 lbs</li></ul>' WHERE `item_no`='50011';
UPDATE `Product_Size` SET `dimension`= 'Cup Diameter<ul><li>18"</li></ul>Flat Dimensions<ul><li>23"x 25"</li></ul>Weight Recommendation<ul><li>up to 30 lbs</li></ul>' WHERE `item_no`='50011';
UPDATE `Product_Size` SET `dimension`= 'Cup Diameter<ul><li>13"</li></ul>Flat Dimensions<ul><li>16"x 18"</li></ul>Weight Recommendation<ul><li>up to 12 lbs</li></ul>' WHERE `item_no`='50012';
UPDATE `Product_Size` SET `dimension`= 'Cup Diameter<ul><li>18"</li></ul>Flat Dimensions<ul><li>23"x 25"</li></ul>Weight Recommendation<ul><li>up to 30 lbs</li></ul>' WHERE `item_no`='50012';
