UPDATE `Product` SET `material`='- Plantation grown and renewable wood<br>- Removable stainless steel liner',`care_instruction`='- Wipe wood body with damp cloth<br>- Stainless steel bowls are dishwasher safe or can be hand washed' WHERE `item_no`=10001;
UPDATE `Product` SET `material`='- Plantation grown and renewable wood<br>- Removable stainless steel liner',`care_instruction`='- Wipe wood body with damp cloth<br>- Stainless steel bowls are dishwasher safe or can be hand washed' WHERE `item_no`=10002;
UPDATE `Product` SET `material`='- Handcrafted aluminum with poloished nickel finish<br>- Removable stainless steel liner',`care_instruction`='- Wipe aluminum body with damp cloth<br>- Stainless steel bowls are dishwasher safe or can be hand washed' WHERE `item_no`=10003;
UPDATE `Product` SET `material`='- Resin<br>- Removable stainless steel liner',`care_instruction`='- Outdoor use should be limited to covered areas only<br>- Avoid extreme temperatures and direct sunlight<br>- Wipe resin body with damp cloth<br>- Stainless steel bowls are dishwasher safe or can be hand washed' WHERE `item_no`=10004;
UPDATE `Product` SET `material`='- Resin<br>- Removable stainless steel liner',`care_instruction`='- Outdoor use should be limited to covered areas only<br>- Avoid extreme temperatures and direct sunlight<br>- Wipe resin body with damp cloth<br>- Stainless steel bowls are dishwasher safe or can be hand washed' WHERE `item_no`=10005;
UPDATE `Product` SET `material`='- Reclaimed steel<br>- Removable stainless steel liner',`care_instruction`='- Wipe reclaimed steel body with damp cloth<br>- Stainless steel bowls are dishwasher safe or can be hand washed' WHERE `item_no`=10006;
UPDATE `Product` SET `material`='- Cast aluminum with a polished nickel finish<br>- Removable stainless steel liner',`care_instruction`='- Wipe aluminum body with damp cloth<br>- Stainless steel bowl is dishwasher safe or can be hand washed' WHERE `item_no`=10007;
UPDATE `Product` SET `material`='- Cast resin<br>- Removable stainless steel liner',`care_instruction`='- Outdoor use should be limited to covered areas only<br>- Avoid extreme temperatures and direct sunlight<br>- Wipe resin body with damp cloth<br>- Stainless steel bowls are dishwasher safe or can be hand washed' WHERE `item_no`=10008;
UPDATE `Product` SET `material`='- Porcelain with nickel finish<br>- Removable stainless steel liner',`care_instruction`='- Wipe porcelain body with damp cloth<br>- Stainless steel bowls are dishwasher safe or an be hand washed' WHERE `item_no`=10009;
UPDATE `Product` SET `material`='- Porcelain <br>- Removable stainless steel liner',`care_instruction`='- Wipe porcelain body with damp cloth<br>- Stainless steel bowls are dishwasher safe or can be hand washed' 
WHERE `item_no`=10010;
UPDATE `Product` SET `material`='- Steel<br>- Removable stainless steel liner',`care_instruction`='- Wipe steel body with damp cloth<br>- Stainless steel bowl is dishwasher safe or can be hand washed' WHERE `item_no`=10011;
UPDATE `Product` SET `material`='- Handmade ceremic',`care_instruction`='- Handwash<br>- Make sure there''s no water trapped inside the bowl after wash' WHERE `item_no`=10012;
UPDATE `Product` SET `material`='- Handmade ceremic',`care_instruction`='- Handwash<br>- Make sure there''s no water trapped inside the bowl after wash' WHERE `item_no`=10013;

UPDATE Product SET material='- US - manufactured marine-grade rope and leather<br>- 100% solid brass hardware',care_instruction='Handwash' WHERE item_no=20001;
UPDATE Product SET material='- US - manufactured marine-grade rope and leather<br>- 100% solid brass hardware',care_instruction='Handwash' WHERE item_no=20002;
UPDATE Product SET material='- US - manufactured marine-grade rope and leather<br>- 100% solid brass hardware',care_instruction='Handwash' WHERE item_no=20003;
UPDATE Product SET material='- US - manufactured marine-grade rope and leather<br>- 100% solid brass hardware',care_instruction='Handwash' WHERE item_no=20004;
UPDATE Product SET material='- US - manufactured marine-grade rope and leather<br>- 100% solid brass hardware',care_instruction='Handwash' WHERE item_no=20005;
UPDATE Product SET material='- US - manufactured marine-grade rope and leather<br>- 100% solid brass hardware',care_instruction='Handwash' WHERE item_no=20006;
UPDATE Product SET material='- 100% cotton waxed canvas and wool<br>- 100% solid brass hardware',care_instruction='Handwash' WHERE item_no=20007;
UPDATE Product SET material='- US - manufactured marine-grade rope and leather<br>- 100% solid brass hardware',care_instruction='Handwash' WHERE item_no=20008;
UPDATE Product SET material='- US - manufactured marine-grade rope and leather ',care_instruction='Handwash' WHERE item_no=20009;
UPDATE Product SET material='- US - manufactured marine-grade rope and leather ',care_instruction='Handwash' WHERE item_no=20010;
UPDATE Product SET material='- US - manufactured marine-grade rope and leather<br>- 100% solid brass hardware',care_instruction='Handwash' WHERE item_no=20011;
UPDATE Product SET material='- US - manufactured marine-grade rope and leather<br>- 100% solid brass hardware',care_instruction='Handwash' WHERE item_no=20012;
UPDATE Product SET material='- US - manufactured marine-grade rope and leather<br>- 100% solid brass hardware',care_instruction='Handwash' WHERE item_no=20013;
UPDATE Product SET material='- US - manufactured marine-grade rope and leather<br>- 100% solid brass hardware',care_instruction='Handwash' WHERE item_no=20014;
UPDATE Product SET material='- US - manufactured marine-grade rope and leather<br>- 100% solid brass hardware',care_instruction='Handwash' WHERE item_no=20015;
UPDATE Product SET material='- US - manufactured marine-grade rope and leather<br>- 100% solid brass hardware',care_instruction='Handwash' WHERE item_no=20016;
UPDATE Product SET material='- US - manufactured marine-grade rope and leather<br>- 100% solid brass hardware',care_instruction='Handwash' WHERE item_no=20017;
UPDATE Product SET material='- US - manufactured marine-grade rope and leather<br>- 100% solid brass hardware',care_instruction='Handwash' WHERE item_no=20018;
UPDATE Product SET material='- US - manufactured marine-grade rope and leather<br>- 100% solid brass hardware',care_instruction='Handwash' WHERE item_no=20019;
UPDATE Product SET material='- US - manufactured marine-grade rope<br>- 100% cotton waxed canvas and wool holding<br>- 100% solid brass hardware',care_instruction='Handwash' WHERE item_no=20020;
UPDATE Product SET material='- US - manufactured marine-grade rope and leather<br>- 100% solid brass hardware',care_instruction='Handwash' WHERE item_no=20021;
UPDATE Product SET material='- US - manufactured marine-grade rope and leather<br>- 100% solid brass hardware',care_instruction='Handwash' WHERE item_no=20022;
UPDATE Product SET material='- US - manufactured marine-grade rope and leather<br>- 100% solid brass hardware',care_instruction='Handwash' WHERE item_no=20023;
UPDATE Product SET material='- Extra strong and safe Buckle<br>- Super soft premium nylon<br>- Rubber Zee Dog feature',care_instruction='Handwash' WHERE item_no=20024;
UPDATE Product SET material='- Extra strong and safe Buckle<br>- Super soft premium nylon<br>- Rubber Zee Dog feature',care_instruction='Handwash' WHERE item_no=20025;
UPDATE Product SET material='- Extra strong and safe Buckle<br>- Super soft premium nylon<br>- Rubber Zee Dog feature',care_instruction='Handwash' WHERE item_no=20026;
UPDATE Product SET material='- Extra strong and safe Buckle<br>- Super soft premium nylon<br>- Rubber Zee Dog feature',care_instruction='Handwash' WHERE item_no=20027;
UPDATE Product SET material='- Extra strong and safe Buckle<br>- Super soft premium nylon<br>- Rubber Zee Dog feature',care_instruction='Handwash' WHERE item_no=20028;
UPDATE Product SET material='- Extra strong and safe Buckle<br>- Super soft premium nylon<br>- Rubber Zee Dog feature',care_instruction='Handwash' WHERE item_no=20029;
UPDATE Product SET material='- Extra strong and safe Buckle<br>- Super soft premium nylon<br>- Rubber Zee Dog feature',care_instruction='Handwash' WHERE item_no=20030;
UPDATE Product SET material='- Extra strong and safe Buckle<br>- Super soft premium nylon<br>- Rubber Zee Dog feature',care_instruction='Handwash' WHERE item_no=20031;
UPDATE Product SET material='- Extra strong and safe Buckle<br>- Super soft premium nylon<br>- Rubber Zee Dog feature',care_instruction='Handwash' WHERE item_no=20032;
UPDATE Product SET material='- Extra strong and safe Buckle<br>- Super soft premium nylon<br>- Rubber Zee Dog feature',care_instruction='Handwash' WHERE item_no=20033;
UPDATE Product SET material='- Extra strong and safe Buckle<br>- Super soft premium nylon<br>- Rubber Zee Dog feature',care_instruction='Handwash' WHERE item_no=20034;
UPDATE Product SET material='- Extra strong and safe Buckle<br>- Super soft premium nylon<br>- Rubber Zee Dog feature',care_instruction='Handwash' WHERE item_no=20035;
UPDATE Product SET material='- Extra strong and safe Buckle<br>- Super soft premium nylon<br>- Rubber Zee Dog feature',care_instruction='Handwash' WHERE item_no=20036;
UPDATE Product SET material='- Extra strong and safe Buckle<br>- Super soft premium nylon<br>- Rubber Zee Dog feature',care_instruction='Handwash' WHERE item_no=20037;
UPDATE Product SET material='- Premium nylon<br>- Power Hook developed by zee dog is heavy duty, rotates 360 degrees and can withstand up to 237kg<br>- Super soft premium nylon<br>- Rubber Zee Dog feature',care_instruction='Handwash' WHERE item_no=20038;
UPDATE Product SET material='- Premium nylon<br>- Power Hook developed by zee dog is heavy duty, rotates 360 degrees and can withstand up to 237kg<br>- Super soft premium nylon<br>- Rubber Zee Dog feature',care_instruction='Handwash' WHERE item_no=20039;
UPDATE Product SET material='- Premium nylon<br>- Power Hook developed by zee dog is heavy duty, rotates 360 degrees and can withstand up to 237kg<br>- Super soft premium nylon<br>- Rubber Zee Dog feature',care_instruction='Handwash' WHERE item_no=20040;
UPDATE Product SET material='- Premium nylon<br>- Power Hook developed by zee dog is heavy duty, rotates 360 degrees and can withstand up to 237kg<br>- Super soft premium nylon<br>- Rubber Zee Dog feature',care_instruction='Handwash' WHERE item_no=20041;
UPDATE Product SET material='- Premium nylon<br>- Power Hook developed by zee dog is heavy duty, rotates 360 degrees and can withstand up to 237kg<br>- Super soft premium nylon<br>- Rubber Zee Dog feature',care_instruction='Handwash' WHERE item_no=20042;
UPDATE Product SET material='- Premium nylon<br>- Power Hook developed by zee dog is heavy duty, rotates 360 degrees and can withstand up to 237kg<br>- Super soft premium nylon<br>- Rubber Zee Dog feature',care_instruction='Handwash' WHERE item_no=20043;
UPDATE Product SET material='- Premium nylon<br>- Power Hook developed by zee dog is heavy duty, rotates 360 degrees and can withstand up to 237kg<br>- Super soft premium nylon<br>- Rubber Zee Dog feature',care_instruction='Handwash' WHERE item_no=20044;
UPDATE Product SET material='- Premium nylon<br>- Power Hook developed by zee dog is heavy duty, rotates 360 degrees and can withstand up to 237kg<br>- Super soft premium nylon<br>- Rubber Zee Dog feature',care_instruction='Handwash' WHERE item_no=20045;
UPDATE Product SET material='- Premium nylon<br>- Power Hook developed by zee dog is heavy duty, rotates 360 degrees and can withstand up to 237kg<br>- Super soft premium nylon<br>- Rubber Zee Dog feature',care_instruction='Handwash' WHERE item_no=20046;
UPDATE Product SET material='- Premium nylon<br>- Power Hook developed by zee dog is heavy duty, rotates 360 degrees and can withstand up to 237kg<br>- Super soft premium nylon<br>- Rubber Zee Dog feature',care_instruction='Handwash' WHERE item_no=20047;
UPDATE Product SET material='- Premium nylon<br>- Power Hook developed by zee dog is heavy duty, rotates 360 degrees and can withstand up to 237kg<br>- Super soft premium nylon<br>- Rubber Zee Dog feature',care_instruction='Handwash' WHERE item_no=20048;
UPDATE Product SET material='- Premium nylon<br>- Power Hook developed by zee dog is heavy duty, rotates 360 degrees and can withstand up to 237kg<br>- Super soft premium nylon<br>- Rubber Zee Dog feature',care_instruction='Handwash' WHERE item_no=20049;
UPDATE Product SET material='- Premium nylon<br>- Power Hook developed by zee dog is heavy duty, rotates 360 degrees and can withstand up to 237kg<br>- Super soft premium nylon<br>- Rubber Zee Dog feature',care_instruction='Handwash' WHERE item_no=20050;
UPDATE Product SET material='- Premium nylon<br>- Power Hook developed by zee dog is heavy duty, rotates 360 degrees and can withstand up to 237kg<br>- Super soft premium nylon<br>- Rubber Zee Dog feature',care_instruction='Handwash' WHERE item_no=20051;
UPDATE Product SET material='- Premium nylon<br>- Power Hook developed by zee dog is heavy duty, rotates 360 degrees and can withstand up to 237kg<br>- Super soft premium nylon<br>- Rubber Zee Dog feature<br>- Thick, soft, neoprene handle',care_instruction='Handwash' WHERE item_no=20052;
UPDATE Product SET material='- Premium nylon<br>- Power Hook developed by zee dog is heavy duty, rotates 360 degrees and can withstand up to 237kg<br>- Super soft premium nylon<br>- Rubber Zee Dog feature<br>- Thick, soft, neoprene handle',care_instruction='Handwash' WHERE item_no=20053;
UPDATE Product SET material='- Premium nylon<br>- Power Hook developed by zee dog is heavy duty, rotates 360 degrees and can withstand up to 237kg<br>- Super soft premium nylon<br>- Rubber Zee Dog feature<br>- Thick, soft, neoprene handle',care_instruction='Handwash' WHERE item_no=20054;
UPDATE Product SET material='- Premium nylon<br>- Power Hook developed by zee dog is heavy duty, rotates 360 degrees and can withstand up to 237kg<br>- Super soft premium nylon<br>- Rubber Zee Dog feature<br>- Thick, soft, neoprene handle',care_instruction='Handwash' WHERE item_no=20055;
UPDATE Product SET material='- Premium nylon<br>- Power Hook developed by zee dog is heavy duty, rotates 360 degrees and can withstand up to 237kg<br>- Super soft premium nylon<br>- Rubber Zee Dog feature<br>- Thick, soft, neoprene handle',care_instruction='Handwash' WHERE item_no=20056;
UPDATE Product SET material='- Premium nylon<br>- Rubber Zee Dog feature<br>- Snap buckle <br>- With 2 D-Rings',care_instruction='Handwash' WHERE item_no=20057;
UPDATE Product SET material='- Premium nylon<br>- Rubber Zee Dog feature<br>- Snap buckle <br>- With 2 D-Rings',care_instruction='Handwash' WHERE item_no=20058;
UPDATE Product SET material='- Premium nylon<br>- Rubber Zee Dog feature<br>- Snap buckle <br>- With 2 D-Rings',care_instruction='Handwash' WHERE item_no=20059;
UPDATE Product SET material='- Premium nylon<br>- Rubber Zee Dog feature<br>- Snap buckle <br>- With 2 D-Rings',care_instruction='Handwash' WHERE item_no=20060;
UPDATE Product SET material='- Premium nylon<br>- Rubber Zee Dog feature<br>- Snap buckle <br>- With 2 D-Rings',care_instruction='Handwash' WHERE item_no=20061;
UPDATE Product SET material='- Premium nylon<br>- Rubber Zee Dog feature<br>- Snap buckle <br>- With 2 D-Rings',care_instruction='Handwash' WHERE item_no=20062;
UPDATE Product SET material='- Premium nylon<br>- Rubber Zee Dog feature<br>- Snap buckle <br>- With 2 D-Rings',care_instruction='Handwash' WHERE item_no=20063;

UPDATE Product SET material='Made using tough and durable Polycarbonate and ABS thermoplastic',care_instruction='Certified 100% dishwasher safe' WHERE item_no=30001;
UPDATE Product SET material='- Filled with eco-friendly, certified-safe PlanetFill filler, made from 100% post-consumer recycled plastic bottles<br>- Ultra-soft velvet material',care_instruction='100% washer and dryer friendly ' WHERE item_no=30002;
UPDATE Product SET material='- Filled with eco-friendly, certified-safe PlanetFill filler, made from 100% post-consumer recycled plastic bottles<br>- Ultra-soft velvet material',care_instruction='100% washer and dryer friendly ' WHERE item_no=30003;
UPDATE Product SET material='- Filled with eco-friendly, certified-safe PlanetFill filler, made from 100% post-consumer recycled plastic bottles<br>- Ultra-soft velvet material',care_instruction='100% washer and dryer friendly ' WHERE item_no=30004;
UPDATE Product SET material='- Filled with eco-friendly, certified-safe PlanetFill filler, made from 100% post-consumer recycled plastic bottles<br>- Ultra-soft velvet material',care_instruction='100% washer and dryer friendly ' WHERE item_no=30005;
UPDATE Product SET material='- Filled with eco-friendly, certified-safe PlanetFill filler, made from 100% post-consumer recycled plastic bottles<br>- Ultra-soft velvet material',care_instruction='100% washer and dryer friendly ' WHERE item_no=30006;
UPDATE Product SET material='- Filled with eco-friendly, certified-safe PlanetFill filler, made from 100% post-consumer recycled plastic bottles<br>- Ultra-soft velvet material',care_instruction='100% washer and dryer friendly ' WHERE item_no=30007;
UPDATE Product SET material='- Filled with eco-friendly, certified-safe PlanetFill filler, made from 100% post-consumer recycled plastic bottles<br>- Ultra-soft velvet material',care_instruction='100% washer and dryer friendly ' WHERE item_no=30008;
UPDATE Product SET material='- Filled with eco-friendly, certified-safe PlanetFill filler, made from 100% post-consumer recycled plastic bottles<br>- Ultra-soft velvet material',care_instruction='100% washer and dryer friendly ' WHERE item_no=30009;
UPDATE Product SET material='- Filled with eco-friendly, certified-safe PlanetFill filler, made from 100% post-consumer recycled plastic bottles<br>- Ultra-soft velvet material',care_instruction='100% washer and dryer friendly ' WHERE item_no=30010;
UPDATE Product SET material='- Filled with eco-friendly, certified-safe PlanetFill filler, made from 100% post-consumer recycled plastic bottles<br>- Ultra-soft velvet material',care_instruction='100% washer and dryer friendly ' WHERE item_no=30011;
UPDATE Product SET material='100% eco-friendly and made from chemical-free natural dyed cotton thread',care_instruction='Machine washable' WHERE item_no=30012;
UPDATE Product SET material='100% eco-friendly and made from chemical-free natural dyed cotton thread',care_instruction='Machine washable' WHERE item_no=30013;
UPDATE Product SET material='100% eco-friendly and made from chemical-free natural dyed cotton thread',care_instruction='Machine washable' WHERE item_no=30014;
UPDATE Product SET material='100% eco-friendly and made from chemical-free natural dyed cotton thread',care_instruction='Machine washable' WHERE item_no=30015;
UPDATE Product SET material='100% eco-friendly and made from chemical-free natural dyed cotton thread',care_instruction='Machine washable' WHERE item_no=30016;
UPDATE Product SET material='100% eco-friendly and made from chemical-free natural dyed cotton thread',care_instruction='Machine washable' WHERE item_no=30017;
UPDATE Product SET material='100% eco-friendly and made from chemical-free natural dyed cotton thread',care_instruction='Machine washable' WHERE item_no=30018;
UPDATE Product SET material='100% eco-friendly and made from chemical-free natural dyed cotton thread',care_instruction='Machine washable' WHERE item_no=30019;
UPDATE Product SET material='100% eco-friendly and made from chemical-free natural dyed cotton thread',care_instruction='Machine washable' WHERE item_no=30020;
UPDATE Product SET material='100% eco-friendly and made from chemical-free natural dyed cotton thread',care_instruction='Machine washable' WHERE item_no=30021;
UPDATE Product SET material='100% eco-friendly and made from chemical-free natural dyed cotton thread',care_instruction='Machine washable' WHERE item_no=30022;
UPDATE Product SET material='100% eco-friendly and made from chemical-free natural dyed cotton thread',care_instruction='Machine washable' WHERE item_no=30023;
UPDATE Product SET material='100% eco-friendly and made from chemical-free natural dyed cotton thread',care_instruction='Machine washable' WHERE item_no=30024;
UPDATE Product SET material='100% eco-friendly and made from chemical-free natural dyed cotton thread',care_instruction='Machine washable' WHERE item_no=30025;
UPDATE Product SET material='100% eco-friendly and made from chemical-free natural dyed cotton thread',care_instruction='Machine washable' WHERE item_no=30026;
UPDATE Product SET material='100% eco-friendly and made from chemical-free natural dyed cotton thread',care_instruction='Machine washable' WHERE item_no=30027;
UPDATE Product SET material='100% eco-friendly and made from chemical-free natural dyed cotton thread',care_instruction='Machine washable' WHERE item_no=30028;
UPDATE Product SET material='100% eco-friendly and made from chemical-free natural dyed cotton thread',care_instruction='Machine washable' WHERE item_no=30029;
UPDATE Product SET material='100% eco-friendly and made from chemical-free natural dyed cotton thread',care_instruction='Machine washable' WHERE item_no=30030;
UPDATE Product SET material='100% eco-friendly and made from chemical-free natural dyed cotton thread',care_instruction='Machine washable' WHERE item_no=30031;
UPDATE Product SET material='100% eco-friendly and made from chemical-free natural dyed cotton thread',care_instruction='Machine washable' WHERE item_no=30032;
UPDATE Product SET material='100% eco-friendly and made from chemical-free natural dyed cotton thread',care_instruction='Machine washable' WHERE item_no=30033;
UPDATE Product SET material='100% eco-friendly and made from chemical-free natural dyed cotton thread',care_instruction='Machine washable' WHERE item_no=30034;
UPDATE Product SET material='100% eco-friendly and made from chemical-free natural dyed cotton thread',care_instruction='Machine washable' WHERE item_no=30035;
UPDATE Product SET material='100% eco-friendly and made from chemical-free natural dyed cotton thread',care_instruction='Machine washable' WHERE item_no=30036;
UPDATE Product SET material='100% eco-friendly and made from chemical-free natural dyed cotton thread',care_instruction='Machine washable' WHERE item_no=30037;
UPDATE Product SET material='100% eco-friendly and made from chemical-free natural dyed cotton thread',care_instruction='Machine washable' WHERE item_no=30038;
UPDATE Product SET material='100% eco-friendly and made from chemical-free natural dyed cotton thread',care_instruction='Machine washable' WHERE item_no=30039;
UPDATE Product SET material='100% eco-friendly and made from chemical-free natural dyed cotton thread',care_instruction='Machine washable' WHERE item_no=30040;
UPDATE Product SET material='100% eco-friendly and made from chemical-free natural dyed cotton thread',care_instruction='Machine washable' WHERE item_no=30041;
UPDATE Product SET material='100% eco-friendly and made from chemical-free natural dyed cotton thread',care_instruction='Machine washable' WHERE item_no=30042;
UPDATE Product SET material='- Made from natural boiled wool<br>- Body made of Polyfill fiber',care_instruction='Machine wash and  Dry' WHERE item_no=30043;
UPDATE Product SET material='- Made from natural boiled wool<br>- Body made of Polyfill fiber',care_instruction='Machine wash and  Dry' WHERE item_no=30044;

UPDATE Product SET material='- 100% Polyester<br>- Moscape Function: anti-mosquito, insecticide, antibacterial deodorant',care_instruction='Handwash' WHERE item_no=40001;
UPDATE Product SET material='- Body: 56% polyester, 41% cotton, 3% polyurethane<br>- Border: 100% Cotton<br>- Rinne function: Health-support by far-infrared waves and negative ion',care_instruction='Handwash' WHERE item_no=40002;
UPDATE Product SET material='- 100% Polyester<br>- Moscape Function: anti-mosquito, insecticide, antibacterial deodorant',care_instruction='Handwash' WHERE item_no=40003;
UPDATE Product SET material='- Body: 56% polyester, 41% cotton, 3% polyurethane<br>- Border: 100% Cotton<br>- Rinne function: Health-support by far-infrared waves and negative ion',care_instruction='Handwash' WHERE item_no=40004;
UPDATE Product SET material='Polyester and cotton',care_instruction='Handwash' WHERE item_no=40005;
UPDATE Product SET material='100% Polyester',care_instruction='Handwash' WHERE item_no=40006;
UPDATE Product SET material='- 60% polyester, 40% cotton<br>- Moscape Function: anti-mosquito, insecticide, antibacterial deodorant',care_instruction='Handwash' WHERE item_no=40007;
UPDATE Product SET material='100% Polyester',care_instruction='Handwash' WHERE item_no=40008;
UPDATE Product SET material='- 100% Polyester<br>- Water-repellent',care_instruction='Handwash' WHERE item_no=40009;

UPDATE Product SET material='- Eco-friendly, certified-safe PlanetFill filler, made from 100% post-consumer recycled plastic bottles<br>- Denim - 62% Cotton and 38% polyester',care_instruction='Machine washable and dryer friendly' WHERE item_no=50001;
UPDATE Product SET material='- Eco-friendly, certified-safe PlanetFill filler, made from 100% post-consumer recycled plastic bottles<br>- Cotton',care_instruction='Machine washable and dryer friendly' WHERE item_no=50002;
UPDATE Product SET material='- Eco-friendly, certified-safe PlanetFill filler, made from 100% post-consumer recycled plastic bottles<br>- Cotton and polyester',care_instruction='Machine washable and dryer friendly' WHERE item_no=50003;
UPDATE Product SET material='- Eco-friendly, certified-safe PlanetFill filler, made from 100% post-consumer recycled plastic bottles<br>- Cotton',care_instruction='Machine washable and dryer friendly' WHERE item_no=50004;
UPDATE Product SET material='- Eco-friendly, certified-safe PlanetFill filler, made from 100% post-consumer recycled plastic bottles<br>- Polyester',care_instruction='Machine washable and dryer friendly' WHERE item_no=50005;
UPDATE Product SET material='- Eco-friendly, certified-safe PlanetFill filler, made from 100% post-consumer recycled plastic bottles<br>- Polyester',care_instruction='Machine washable and dryer friendly' WHERE item_no=50006;
UPDATE Product SET material='- Eco-friendly, certified-safe PlanetFill filler, made from 100% post-consumer recycled plastic bottles<br>- Cotton and Polyester',care_instruction='Machine washable and dryer friendly' WHERE item_no=50007;
UPDATE Product SET material='- Eco-friendly, certified-safe PlanetFill filler, made from 100% post-consumer recycled plastic bottles<br>- Cotton',care_instruction='Machine washable and dryer friendly' WHERE item_no=50008;
UPDATE Product SET material='- Eco-friendly, certified-safe PlanetFill filler, made from 100% post-consumer recycled plastic bottles<br>- Cotton',care_instruction='Machine washable and dryer friendly' WHERE item_no=50009;
UPDATE Product SET material='Cotton canvas and faux fur',care_instruction='Machine washable and dryer friendly' WHERE item_no=50010;
UPDATE Product SET material='Cotton canvas and faux fur',care_instruction='Machine washable and dryer friendly' WHERE item_no=50011;
UPDATE Product SET material='Cotton canvas and faux fur',care_instruction='Machine washable and dryer friendly' WHERE item_no=50012;
